#ifndef LEVEL6_H
#define LEVEL6_H

// ============================================================
// LEVEL 6 
// ============================================================

static const LevelData LEVEL_6_DATA = {
    .name = "Break a Leg",

    // Map segments (auto-generated by chunk_glb.py)
    .segments = {
        "rom:/level6_chunk0.t3dm",
        "rom:/level6_chunk1.t3dm",
        "rom:/level6_chunk2.t3dm",
        "rom:/level6_chunk3.t3dm",
        "rom:/level6_chunk4.t3dm",
        "rom:/level6_chunk5.t3dm",
        "rom:/level6_chunk6.t3dm",
        "rom:/level6_chunk7.t3dm",
        "rom:/level6_chunk8.t3dm",
        "rom:/level6_chunk9.t3dm",
        "rom:/level6_chunk10.t3dm",
        "rom:/level6_chunk11.t3dm",
        "rom:/level6_chunk12.t3dm"
    },
    .segmentCount = 13,

    // Extra rotation to orient level correctly (same as level 3)
    .mapRotY = 90.0f,

    // Decorations - add your decorations here
    .decorations = {
{ DECO_PLAYERSPAWN, 1626.9f, 627.5f, 0.1f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, -4948.5f, 879.6f, 454.1f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_GRINDER, -4314.4f, 749.4f, 286.8f, -0.00f, 1.00f, 1.00f, 0.64f },
{ DECO_GRINDER, -4434.6f, 749.4f, 286.8f, -3.14f, 1.00f, 1.00f, 0.64f },
{ DECO_GRINDER, -5304.0f, 677.2f, 431.4f, -0.00f, 1.00f, 1.00f, 1.54f },
{ DECO_GRINDER, -5397.9f, 677.2f, 431.4f, -3.14f, 1.00f, 1.00f, 1.54f },
{ DECO_LAVAFLOOR, 1234.6f, 469.5f, 102.5f, -0.00f, 0.84f, 0.84f, 0.84f },
{ DECO_LAVAFLOOR, 540.5f, 469.5f, -100.0f, -0.00f, 0.53f, 0.65f, 0.56f },
{ DECO_LAVAFLOOR, -2998.0f, 347.1f, -281.0f, -0.00f, 1.00f, 1.00f, 1.19f },
{ DECO_LAVAFLOOR, -4767.1f, 570.4f, 173.0f, -0.00f, 0.63f, 0.96f, 0.70f },
{ DECO_LAVAFALLS, 1277.2f, 462.2f, 485.5f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_LAVAFALLS, 688.2f, 459.2f, 70.4f, 3.14f, 1.26f, 2.59f, 1.26f },
{ DECO_LAVAFALLS, -3148.8f, 329.3f, -458.2f, 3.14f, 1.06f, 1.76f, 1.20f },
{ DECO_LAVAFALLS, -4944.2f, 558.6f, 414.6f, 3.14f, 2.66f, 3.24f, 1.91f },
{ DECO_CONVEYERLARGE, 668.3f, 587.4f, -74.8f, -0.00f, 1.00f, 1.00f, 0.65f },
{ DECO_SINK_PLAT, 387.3f, 618.4f, 75.7f, -1.57f, 1.00f, 1.00f, 1.00f },
{ DECO_SPINNER, -1658.3f, 503.8f, 46.0f, 2.72f, 1.45f, 1.27f, 1.45f },
{ DECO_SPINNER, -1658.3f, 909.3f, 46.0f, 2.72f, 1.45f, 1.27f, 1.45f },
{ DECO_SINK_PLAT, 37.0f, 618.4f, 75.7f, -1.57f, 1.00f, 1.00f, 1.00f },
{ DECO_SINK_PLAT, -316.0f, 618.4f, 75.7f, -1.57f, 1.00f, 1.00f, 2.91f },
{ DECO_TURRET, -1575.6f, 641.9f, 82.8f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_DAMAGECOLLISION, -5362.5f, 554.2f, 428.7f, -0.00f, 3.11f, 5.10f, 3.60f },
{ DECO_BULLDOZER, 218.2f, 618.7f, 26.3f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_SPINNER, -6518.7f, 1146.2f, 437.9f, 2.72f, 1.45f, 1.27f, 1.45f },
{ DECO_SPINNER, -6518.7f, 1708.2f, 437.9f, 2.72f, 1.45f, 1.27f, 1.45f },
{ DECO_LAVAFLOOR, -1669.1f, 40.5f, 74.0f, -0.00f, 0.56f, 0.56f, 0.56f },
{ DECO_SINK_PLAT, -4850.5f, 849.6f, 312.4f, 3.14f, 0.80f, 0.80f, 1.11f },
{ DECO_LAVAFLOOR, -4.8f, 469.5f, -100.0f, -0.00f, 0.53f, 0.65f, 0.56f },
{ DECO_LAVAFLOOR, -550.1f, 469.5f, -100.0f, -0.00f, 0.53f, 0.65f, 0.56f },
{ DECO_LAVAFLOOR, -5358.0f, 570.4f, 376.5f, -0.00f, 0.19f, 0.20f, 0.26f },
{ DECO_LAVAFLOOR, -4118.1f, 570.4f, 173.0f, -0.00f, 0.63f, 0.96f, 0.70f },
{ DECO_CHARGEPAD, -3427.8f, 521.9f, -144.5f, -0.00f, 1.59f, 1.59f, 1.59f },
{ DECO_MOVE_PLAT, -2587.6f, 605.5f, 273.9f, -1.57f, 0.81f, 1.00f, 1.14f, .platformTargetX = -2587.6f, .platformTargetY = 856.9f, .platformTargetZ = 273.9f, .platformSpeed = 60.0f, .activationId = 1, .startStationary = true },
{ DECO_ROUNDBUTTON, -3385.4f, 519.3f, 107.3f, -0.00f, 1.00f, 1.00f, 1.00f, .activationId = 1 },
{ DECO_LIGHT_TRIGGER_PERMANENT, 1620.3f, 670.4f, 5.6f, -0.00f, 2.55f, 2.55f, 2.55f, .checkpointAmbientR = 9, .checkpointAmbientG = 1, .checkpointAmbientB = 0, .checkpointDirectionalR = 255, .checkpointDirectionalG = 131, .checkpointDirectionalB = 41, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 0.50f, .lightTriggerDirZ = -1.00f },
{ DECO_BOLT, 215.8f, 751.0f, 132.3f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, 680.9f, 850.1f, 135.6f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_DAMAGECOLLISION, 373.4f, 355.3f, -61.6f, -0.00f, 42.89f, 3.42f, 27.13f },
{ DECO_MOVE_PLAT, -5181.5f, 906.8f, 267.2f, 3.14f, 0.62f, 1.00f, 1.14f, .platformTargetX = -5181.5f, .platformTargetY = 1113.9f, .platformTargetZ = 267.2f, .platformSpeed = 60.0f },
{ DECO_MOVE_PLAT, -5215.4f, 1089.8f, 549.0f, -1.57f, 0.62f, 0.76f, 0.75f, .platformTargetX = -5215.4f, .platformTargetY = 1335.1f, .platformTargetZ = 549.0f, .platformSpeed = 60.0f },
{ DECO_CHARGEPAD, -3061.3f, 918.5f, 407.9f, -0.00f, 1.59f, 1.59f, 1.59f },
{ DECO_BULLDOZER, -2969.8f, 930.4f, 398.0f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BULLDOZER, -3168.1f, 930.4f, 398.0f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_LAVAFLOOR, -6504.5f, 639.1f, 421.3f, -0.00f, 0.81f, 0.67f, 1.00f },
{ DECO_BOLT, 1196.8f, 878.8f, -48.5f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_CHARGEPAD, 1473.5f, 784.4f, 244.4f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_CHECKPOINT, -2372.8f, 676.5f, 5.7f, -0.00f, 3.94f, 2.98f, 4.49f },
{ DECO_DAMAGECOLLISION, -4447.8f, 492.5f, 192.2f, -0.00f, 20.11f, 2.46f, -10.47f },
{ DECO_DAMAGECOLLISION, -3041.9f, 173.3f, -217.4f, -0.00f, 20.11f, 5.37f, -22.84f },
{ DECO_LAVAFLOOR, -5365.1f, 570.4f, 414.3f, -0.00f, 0.30f, 0.45f, 0.33f },
{ DECO_TRANSITIONCOLLISION, -7206.5f, 1558.5f, 445.3f, -0.00f, 3.36f, 3.36f, 3.36f, .targetLevel = 6 },
{ DECO_FAN2, -5433.9f, 828.7f, 217.3f, 3.14f, 0.48f, 0.60f, 0.69f },
{ DECO_FAN2, -5433.9f, 828.7f, 269.6f, 3.14f, 0.48f, 0.60f, 0.69f },
{ DECO_LASERWALL, -6728.3f, 1397.1f, 452.7f, 3.14f, 1.96f, 1.23f, 1.35f, .activationId = 2 },
{ DECO_LASERWALL, -7010.2f, 1455.8f, 452.7f, 3.14f, 1.96f, 1.23f, 1.35f, .activationId = 3 },
{ DECO_BOLT, 1276.2f, 498.9f, 405.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_SCREWG, -3155.4f, 881.3f, -139.5f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_DAMAGECUBE_LIGHT, -2969.1f, 466.9f, 36.9f, 3.14f, 1.84f, 1.92f, 6.87f },
{ DECO_DAMAGECUBE_LIGHT, -3152.8f, 801.5f, -110.7f, 3.14f, 1.84f, 1.98f, 11.13f },
{ DECO_DAMAGECUBE_LIGHT, -3152.8f, 572.1f, 194.8f, 3.14f, 1.84f, 8.98f, 1.60f },
{ DECO_DAMAGECUBE_LIGHT, -3001.1f, 466.9f, -130.8f, 3.14f, 6.48f, 1.94f, 1.79f },
{ DECO_DAMAGECUBE_LIGHT, -2764.4f, 538.5f, -130.8f, 3.14f, 3.25f, 1.89f, 1.58f },
{ DECO_BOLT, -4671.5f, 681.6f, 197.4f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_DROID_SEC, -6433.1f, 1364.6f, 549.3f, 3.14f, 1.00f, 1.00f, 1.00f, .activationId = 2 },
{ DECO_DROID_SEC, -6433.1f, 1364.6f, 356.9f, 3.14f, 1.00f, 1.00f, 1.00f, .activationId = 3 },
{ DECO_BULLDOZER, -1729.9f, 598.8f, 11.9f, -0.00f, 2.15f, 2.15f, 2.15f },
{ DECO_BOLT, -2598.4f, 414.4f, -272.2f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, -1825.0f, 758.9f, -169.3f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_LIGHT_TRIGGER, -1642.1f, 638.7f, 47.1f, -0.00f, 11.90f, 11.90f, 11.90f, .checkpointAmbientR = 131, .checkpointAmbientG = 71, .checkpointAmbientB = 40, .checkpointDirectionalR = 44, .checkpointDirectionalG = 90, .checkpointDirectionalB = 113, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -1.00f },
{ DECO_FOGCOLOR, -1011.6f, 638.7f, -4.7f, -0.00f, 1.83f, 3.74f, 6.57f, .fogColorR = 10, .fogColorG = 31, .fogColorB = 55 },
{ DECO_FOGCOLOR, -2289.7f, 638.7f, -4.7f, -0.00f, 1.83f, 3.74f, 6.57f, .fogColorR = 10, .fogColorG = 31, .fogColorB = 55 },
{ DECO_FOGCOLOR, -827.7f, 638.7f, -4.7f, -0.00f, 1.83f, 3.74f, 6.57f, .fogColorR = 241, .fogColorG = 38, .fogColorB = 8},
{ DECO_FOGCOLOR, -2442.0f, 638.7f, -4.7f, -0.00f, 1.83f, 3.74f, 6.57f, .fogColorR = 241, .fogColorG = 38, .fogColorB = 8},
{ DECO_TURRET, 660.1f, 600.5f, 135.5f, -0.00f, 1.00f, 1.00f, 1.00f },



    },
    .decorationCount = 74,

    // Player start position
    .playerStartX = 0.0f,
    .playerStartY = 100.0f,
    .playerStartZ = 0.0f,

    // Background music
    .music = "rom:/N64JetForceTrack.wav64",

    // Body part (1 = torso, 2 = arms, 3 = fullbody/legs)
    .bodyPart = 3,

    // Point light (optional, set hasPointLight = true to enable)
    .hasPointLight = false,
    .lightX = 0.0f,
    .lightY = 0.0f,
    .lightZ = 0.0f,

    // Directional light direction (0,0,0 = default 1,1,1 diagonal)
    // This is a vector pointing TOWARD the light source
    // Examples: (0,1,0) = noon sun, (1,0.5,0) = low side angle
    .lightDirX = -0.2f,
    .lightDirY = 0.5f,
    .lightDirZ = -1.0f,

    // Ambient light color RGB 0-255 (0,0,0 = default 80,80,80 gray)
    .ambientR = 0,
    .ambientG = 0,
    .ambientB = 0,

    // Directional light color RGB 0-255 (0,0,0 = default 255,255,255 white)
    .directionalR = 0,
    .directionalG = 0,
    .directionalB = 0,

    // Background/clear color RGB 0-255 (black default)
    .bgR = 0,
    .bgG = 0,
    .bgB = 0,

    // Fog settings - lava colored fog
    .fogEnabled = true,
    .fogR = 200,
    .fogG = 60,
    .fogB = 20,
    .fogNear = 100.0f,
    .fogFar = 600.0f,
};

#endif // LEVEL6_H
