#ifndef LEVEL4_H
#define LEVEL4_H

// ============================================================
// LEVEL 4
// ============================================================

static const LevelData LEVEL_4_DATA = {
    .name = "Armed and Dangerous",

    // Map segments (auto-generated by chunk_glb.py)
    .segments = {
        "rom:/level4_chunk0.t3dm",
        "rom:/level4_chunk1.t3dm",
        "rom:/level4_chunk2.t3dm",
        "rom:/level4_chunk3.t3dm",
        "rom:/level4_chunk4.t3dm",
        "rom:/level4_chunk5.t3dm",
        "rom:/level4_chunk6.t3dm",
        "rom:/level4_chunk7.t3dm",
        "rom:/level4_chunk8.t3dm",
        "rom:/level4_chunk9.t3dm",
        "rom:/level4_chunk10.t3dm",
        "rom:/level4_chunk11.t3dm",
        "rom:/level4_chunk12.t3dm"
    },
    .segmentCount = 13,

    // Extra rotation to orient level correctly
    .mapRotY = 90.0f,

    // Decorations - add your decorations here
    .decorations = {
       { DECO_PLAYERSPAWN, 1219.8f, 1553.2f, -154.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, 980.3f, 1685.1f, 39.1f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_MOVE_COAL, -1426.8f, 1810.4f, 70.7f, 3.14f, 0.50f, 0.50f, 0.50f, .platformTargetX = -1426.8f, .platformTargetY = 1483.7f, .platformTargetZ = 70.7f, .platformSpeed = 60.0f, .activationId = 1 },
{ DECO_TRANSITIONCOLLISION, -6944.2f, 69.3f, 619.6f, -0.00f, 1.64f, 1.64f, 1.64f, .targetLevel = 4 },
{ DECO_ROUNDBUTTON, 222.7f, 1634.5f, 80.5f, 3.14f, 0.88f, 0.88f, 0.88f, .activationId = 1 },
{ DECO_RAT, 872.5f, 1508.6f, -233.1f, 3.14f, 1.90f, 1.90f, 1.90f },
{ DECO_CONVEYERLARGE, 448.7f, 1497.7f, -148.8f, -3.14f, 1.35f, 2.07f, 1.57f },
{ DECO_BULLDOZER, -1256.6f, 1479.4f, -130.3f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_LASERWALL, -478.0f, 1525.6f, -152.5f, -0.00f, 2.22f, 1.02f, 1.24f, .activationId = 1 },
{ DECO_GRINDER, 478.6f, 1599.8f, -148.3f, -0.00f, 1.47f, 1.47f, 1.26f },
{ DECO_CONVEYERLARGE, 5.8f, 1497.7f, -148.8f, -3.14f, 1.35f, 2.07f, 1.57f },
{ DECO_CONVEYERLARGE, -438.1f, 1497.7f, -148.8f, -3.14f, 1.35f, 2.07f, 1.57f },
{ DECO_LAVAFALLS, -2811.4f, 1356.5f, 646.8f, 2.94f, 2.39f, 2.90f, 3.73f },
{ DECO_LAVAFLOOR, -2162.3f, 1390.5f, 690.2f, -0.00f, 1.23f, 1.16f, 1.03f },
{ DECO_TURRET, 792.5f, 1515.3f, 74.2f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_COG, -300.5f, 1530.0f, 9.6f, -0.00f, 1.58f, 1.58f, 3.24f },
{ DECO_LAVAFLOOR, -3424.8f, 1390.5f, 690.2f, -0.00f, 1.23f, 1.16f, 1.03f },
{ DECO_LAVAFLOOR, -4687.2f, 1390.5f, 690.2f, -0.00f, 1.23f, 1.16f, 1.03f },
{ DECO_LAVAFALLS, -4632.2f, 1672.0f, 981.1f, 3.14f, 1.27f, 1.98f, 1.98f },
{ DECO_LAVAFALLS, -1967.7f, 1356.5f, 831.2f, 2.78f, 3.19f, 1.70f, 5.18f },
{ DECO_LAVAFALLS, -3783.1f, 1341.3f, 748.0f, 2.73f, 2.30f, 3.79f, 8.83f },
{ DECO_MOVE_COAL, -1087.5f, 1465.5f, 72.0f, 3.14f, 0.50f, 0.50f, 0.50f, .platformTargetX = -1087.5f, .platformTargetY = 1814.4f, .platformTargetZ = 72.0f, .platformSpeed = 60.0f, .activationId = 1 },
{ DECO_FAN2, 443.3f, 1442.5f, -284.9f, 3.14f, 0.60f, 0.60f, 0.60f },
{ DECO_FAN2, -3112.3f, 1493.3f, 407.6f, 3.14f, 0.61f, 0.61f, 0.61f },
{ DECO_LAVA_RIVER, -4629.9f, 1570.3f, 720.4f, 3.14f, 1.03f, 1.00f, 1.03f },
{ DECO_FLOATING_ROCK, -2111.8f, 1373.8f, 613.5f, 2.64f, 0.70f, 1.10f, 0.70f },
{ DECO_SPIN_ROCK, -2610.6f, 1397.6f, 328.3f, -0.00f, 0.66f, 1.16f, 0.66f },
{ DECO_SPIN_ROCK2, -2762.4f, 1398.6f, 364.9f, -0.00f, 1.00f, 1.15f, 1.00f },
{ DECO_FLOATING_ROCK2, -2052.7f, 1430.2f, 779.7f, 1.38f, 1.00f, 1.14f, 1.00f },
{ DECO_SPIN_ROCK, -2768.8f, 1398.5f, 557.8f, -0.00f, 0.65f, 1.21f, 0.65f },
{ DECO_SPIN_ROCK2, -2943.8f, 1396.0f, 537.0f, -0.00f, 0.63f, 0.82f, 0.63f },
{ DECO_FLOATING_ROCK2, -3213.7f, 1411.0f, 533.2f, -1.21f, 0.60f, 0.60f, 0.60f },
{ DECO_SPIN_ROCK, -4653.5f, 1340.7f, 419.4f, -0.00f, 0.71f, 1.26f, 0.71f },
{ DECO_BOLT, -1738.3f, 1641.1f, 59.4f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_MOVE_COAL, -1741.7f, 1638.8f, 53.0f, 3.14f, 0.50f, 0.50f, 0.50f, .platformTargetX = -1741.7f, .platformTargetY = 1444.7f, .platformTargetZ = 53.0f, .platformSpeed = 60.0f, .activationId = 2, .startStationary = true },
{ DECO_ROUNDBUTTON, -1624.8f, 1458.6f, -67.0f, -0.00f, 0.88f, 0.88f, 0.88f, .activationId = 2 },
{ DECO_BOLT, -1890.3f, 1545.0f, 659.8f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, -3221.9f, 1746.2f, 676.3f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_FLOATING_ROCK2, -3420.2f, 1425.2f, 628.9f, -2.72f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, -5107.9f, 1857.8f, 1016.7f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_SLIME_LAVA, -4756.6f, 1858.5f, 1050.8f, -2.09f, 1.00f, 1.00f, 1.00f },
{ DECO_SLIME_LAVA, -4626.8f, 1544.8f, 615.7f, -3.05f, 1.00f, 1.00f, 1.00f },
{ DECO_CONVEYERLARGE, -6325.2f, 30.8f, 450.5f, 0.00f, 1.35f, 2.07f, 1.57f },
{ DECO_CHECKPOINT, -2302.9f, 1504.4f, 107.6f, -0.00f, 3.65f, 4.22f, 0.46f },
{ DECO_HANGING_L, -1652.6f, 1439.6f, -208.1f, -1.68f, 1.00f, 1.00f, 1.00f },
{ DECO_HANGING_L, -1932.9f, 1467.9f, -176.1f, -2.17f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, -79.7f, 1336.9f, -315.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_TURRET, -1834.4f, 1519.8f, 6.0f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_SPIN_ROCK, -2298.3f, 1402.8f, 537.4f, -0.00f, 0.73f, 1.08f, 0.73f },
{ DECO_FAN2, -4392.1f, 1544.4f, 502.9f, 3.14f, 0.61f, 0.61f, 0.61f },
{ DECO_BOLT, -3792.5f, 1515.0f, 407.3f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BULLDOZER, -6597.5f, 55.5f, 623.4f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, -6417.9f, 78.1f, 776.6f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -544.8f, 1504.4f, -147.5f, -0.00f, 1.17f, 4.22f, 2.67f, .checkpointAmbientR = 6, .checkpointAmbientG = 10, .checkpointAmbientB = 33, .checkpointDirectionalR = 89, .checkpointDirectionalG = 181, .checkpointDirectionalB = 255, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 0.50f, .lightTriggerDirZ = -1.00f },
{ DECO_LIGHT_TRIGGER_PERMANENT, 1203.1f, 1595.0f, -147.5f, -0.00f, 3.37f, 4.22f, 2.67f, .checkpointAmbientR = 6, .checkpointAmbientG = 10, .checkpointAmbientB = 33, .checkpointDirectionalR = 255, .checkpointDirectionalG = 248, .checkpointDirectionalB = 218, .lightTriggerDirX = -1.00f, .lightTriggerDirY = 0.00f, .lightTriggerDirZ = -0.50f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -46.8f, 1504.4f, -147.5f, -0.00f, 1.96f, 4.22f, 3.14f, .checkpointAmbientR = 6, .checkpointAmbientG = 10, .checkpointAmbientB = 33, .checkpointDirectionalR = 255, .checkpointDirectionalG = 248, .checkpointDirectionalB = 218, .lightTriggerDirX = -1.00f, .lightTriggerDirY = 0.00f, .lightTriggerDirZ = -0.50f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -2307.9f, 1527.9f, 161.3f, -0.00f, 2.57f, 2.56f, 0.57f, .checkpointAmbientR = 11, .checkpointAmbientG = 1, .checkpointAmbientB = 1, .checkpointDirectionalR = 255, .checkpointDirectionalG = 72, .checkpointDirectionalB = 19, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -0.30f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -5761.3f, 2054.2f, 483.6f, -0.00f, 4.34f, 9.64f, 6.27f, .checkpointAmbientR = 6, .checkpointAmbientG = 10, .checkpointAmbientB = 33, .checkpointDirectionalR = 25, .checkpointDirectionalG = 153, .checkpointDirectionalB = 255, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -1.00f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -5265.4f, 1790.9f, 397.7f, -0.00f, 3.24f, 4.22f, 6.12f, .checkpointAmbientR = 11, .checkpointAmbientG = 1, .checkpointAmbientB = 1, .checkpointDirectionalR = 255, .checkpointDirectionalG = 72, .checkpointDirectionalB = 19, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -0.30f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -6165.1f, 153.7f, 476.9f, -0.00f, 3.37f, 4.22f, 5.80f, .checkpointAmbientR = 6, .checkpointAmbientG = 10, .checkpointAmbientB = 33, .checkpointDirectionalR = 255, .checkpointDirectionalG = 248, .checkpointDirectionalB = 218, .lightTriggerDirX = 1.00f, .lightTriggerDirY = 0.00f, .lightTriggerDirZ = -0.50f },
{ DECO_FOGCOLOR, -2297.8f, 1527.9f, 33.4f, -0.00f, 1.74f, 1.19f, 1.68f, .fogColorR = 255, .fogColorG = 16, .fogColorB = 11 },
{ DECO_FOGCOLOR, -1970.9f, 1561.4f, 16.8f, -0.00f, 0.78f, 3.41f, 2.83f, .fogColorR = 13, .fogColorG = 123, .fogColorB = 255},
{ DECO_FOGCOLOR, 1150.0f, 1527.9f, -151.8f, -0.00f, 4.49f, 5.23f, 4.34f, .fogColorR = 13, .fogColorG = 123, .fogColorB = 255 },
{ DECO_FOGCOLOR, -5858.8f, 2040.7f, 422.0f, -0.00f, 4.49f, 5.23f, 4.34f, .fogColorR = 13, .fogColorG = 123, .fogColorB = 255},
{ DECO_FOGCOLOR, -5317.4f, 1814.1f, 416.3f, -0.00f, 3.62f, 4.22f, 3.50f, .fogColorR = 255, .fogColorG = 16, .fogColorB = 11},
{ DECO_LIGHT_TRIGGER_PERMANENT, -2071.8f, 1583.2f, -2.3f, -0.00f, 0.74f, 4.22f, 3.89f, .checkpointAmbientR = 6, .checkpointAmbientG = 10, .checkpointAmbientB = 33, .checkpointDirectionalR = 89, .checkpointDirectionalG = 181, .checkpointDirectionalB = 255, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 0.50f, .lightTriggerDirZ = -1.00f },
{ DECO_LIGHT_TRIGGER, -4635.2f, 1821.7f, 903.0f, -0.00f, 12.10f, 14.13f, 14.06f, .checkpointAmbientR = 6, .checkpointAmbientG = 10, .checkpointAmbientB = 33, .checkpointDirectionalR = 82, .checkpointDirectionalG = 178, .checkpointDirectionalB = 255, .lightTriggerDirX = 0.00f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -1.00f },
{ DECO_SCREWG, -1250.8f, 1878.4f, 167.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_RAT, -5030.7f, 1826.7f, 988.9f, 3.14f, 1.90f, 1.90f, 1.90f },
{ DECO_RAT, -4813.1f, 1765.9f, 734.3f, 3.14f, 1.90f, 1.90f, 1.90f },


    },
    .decorationCount = 70,

    // Player start position
    .playerStartX = 0.0f,
    .playerStartY = 100.0f,
    .playerStartZ = 0.0f,

    // Background music
    .music = "rom:/scrap1-level1(full).wav64",

    // Body part (1 = torso, 2 = arms, 3 = fullbody/legs)
    .bodyPart = 2,

    // Point light (optional, set hasPointLight = true to enable)
    .hasPointLight = false,
    .lightX = 0.0f,
    .lightY = 0.0f,
    .lightZ = 0.0f,

    // Directional light direction (0,0,0 = default 1,1,1 diagonal)
    // This is a vector pointing TOWARD the light source
    // Examples: (0,1,0) = noon sun, (1,0.5,0) = low side angle
    .lightDirX = -0.2f,
    .lightDirY = 0.5f,
    .lightDirZ = -1.0f,

    // Ambient light color RGB 0-255 (0,0,0 = default 80,80,80 gray)
    .ambientR = 0,
    .ambientG = 0,
    .ambientB = 0,

    // Directional light color RGB 0-255 (0,0,0 = default 255,255,255 white)
    .directionalR = 0,
    .directionalG = 0,
    .directionalB = 0,

    // Background/clear color RGB 0-255 (black default)
    .bgR = 0,
    .bgG = 0,
    .bgB = 0,

    // Fog settings - cave blue pastel atmosphere
    .fogEnabled = true,
    .fogR = 140,
    .fogG = 170,
    .fogB = 200,
    .fogNear = 200,
    .fogFar = 900,
};

#endif // LEVEL4_H
