#ifndef LEVEL5_H
#define LEVEL5_H

// ============================================================
// LEVEL 5 - New Level
// ============================================================

static const LevelData LEVEL_5_DATA = {
    .name = "Reach for the Sky",

    // Map segments (auto-generated by chunk_glb.py)
    .segments = {
        "rom:/level5_chunk0.t3dm",
        "rom:/level5_chunk1.t3dm",
        "rom:/level5_chunk2.t3dm",
        "rom:/level5_chunk3.t3dm",
        "rom:/level5_chunk4.t3dm",
        "rom:/level5_chunk5.t3dm",
        "rom:/level5_chunk6.t3dm",
        "rom:/level5_chunk7.t3dm",
        "rom:/level5_chunk8.t3dm",
        "rom:/level5_chunk9.t3dm",
        "rom:/level5_chunk10.t3dm",
        "rom:/level5_chunk11.t3dm",
        "rom:/level5_chunk12.t3dm",
        "rom:/level5_chunk13.t3dm"
    },
    .segmentCount = 14,

    // Extra rotation to orient level correctly (same as level 3)
    .mapRotY = 90.0f,

    // Decorations - add your decorations here
    .decorations = {
        { DECO_LASERWALL, 1991.2f, 1656.7f, 458.1f, -0.47f, 0.98f, 0.98f, 0.98f, .activationId = 1 },
{ DECO_CONVEYERLARGE, -1420.1f, 1656.6f, 534.3f, -0.00f, 1.13f, 1.00f, 1.00f },
{ DECO_CONVEYERLARGE, -1791.2f, 1656.6f, 534.3f, -0.00f, 1.13f, 1.00f, 1.00f },
{ DECO_CONVEYERLARGE, -2162.0f, 1656.6f, 534.3f, -0.00f, 1.13f, 1.00f, 1.00f },
{ DECO_CONVEYERLARGE, -3623.9f, 1656.6f, 719.5f, -3.14f, 1.13f, 1.00f, 1.00f },
{ DECO_CONVEYERLARGE, -3252.8f, 1656.6f, 719.5f, -3.14f, 1.13f, 1.00f, 1.00f },
{ DECO_CONVEYERLARGE, -2882.1f, 1656.6f, 719.5f, -3.14f, 1.13f, 1.00f, 1.00f },
{ DECO_BOLT, 2362.4f, 1853.3f, 468.0f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_PLAYERSPAWN, 3454.0f, 1716.1f, 147.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_HANGING_L, -1736.6f, 1693.3f, 684.8f, 1.46f, 1.00f, 1.00f, 1.00f },
{ DECO_HANGING_S, -2517.9f, 1659.6f, 650.7f, 0.18f, 1.47f, 1.47f, 1.47f },
{ DECO_HANGING_L, -2129.2f, 1693.3f, 680.0f, 1.74f, 1.00f, 1.00f, 1.00f },
{ DECO_HANGING_L, -3252.0f, 1664.9f, 602.3f, 1.54f, 1.00f, 1.00f, 1.00f },
{ DECO_HANGING_S, -5198.7f, 1804.2f, 651.0f, -1.31f, 0.92f, 0.92f, 0.92f },
{ DECO_BOLT, -1936.2f, 1756.8f, 700.8f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_SCREWG, -5755.9f, 1763.9f, 582.3f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_TRANSITIONCOLLISION, -6485.6f, 1798.6f, 877.5f, -0.00f, 4.28f, 2.09f, 3.40f, .targetLevel = 5 },
{ DECO_MOVING_ROCK, -1293.8f, 1853.9f, 551.8f, 3.14f, 1.00f, 1.00f, 1.00f, .waypoint1X = -1304.2f, .waypoint1Y = 1694.8f, .waypoint1Z = 531.5f, .waypoint2X = -2377.6f, .waypoint2Y = 1694.3f, .waypoint2Z = 531.5f, .waypoint3X = -2394.3f, .waypoint3Y = -3364.7f, .waypoint3Z = 531.5f, .waypointCount = 4, .platformSpeed = 50.0f },
{ DECO_MOVING_ROCK, -3727.9f, 1876.6f, 735.1f, 3.14f, 1.00f, 1.00f, 1.00f, .waypoint1X = -3728.4f, .waypoint1Y = 1698.2f, .waypoint1Z = 718.9f, .waypoint2X = -2654.4f, .waypoint2Y = 1697.5f, .waypoint2Z = 718.9f, .waypoint3X = -2654.4f, .waypoint3Y = -3436.0f, .waypoint3Z = 718.9f, .waypointCount = 4, .platformSpeed = 50.0f },
{ DECO_HANGING_S, 1129.8f, 1370.0f, 410.5f, 0.18f, 1.47f, 1.47f, 1.47f },
{ DECO_MOVE_COAL, -118.6f, 1376.7f, 471.4f, 3.08f, 0.50f, 0.50f, 0.50f, .platformTargetX = -118.6f, .platformTargetY = 1953.1f, .platformTargetZ = 471.4f, .platformSpeed = 60.0f },
{ DECO_MOVE_COAL, -238.2f, 1955.2f, 487.9f, 3.13f, 0.50f, 0.50f, 0.50f, .platformTargetX = -238.2f, .platformTargetY = 1379.8f, .platformTargetZ = 487.9f, .platformSpeed = 60.0f },
{ DECO_MOVE_COAL, -539.1f, 1881.8f, 505.9f, -2.97f, 0.50f, 0.50f, 0.50f, .platformTargetX = -539.1f, .platformTargetY = 1456.1f, .platformTargetZ = 505.9f, .platformSpeed = 60.0f },
{ DECO_MOVE_COAL, -652.1f, 1489.9f, 486.5f, -2.96f, 0.50f, 0.50f, 0.50f, .platformTargetX = -652.1f, .platformTargetY = 1841.3f, .platformTargetZ = 486.5f, .platformSpeed = 60.0f },
{ DECO_BOLT, -5208.8f, 1579.1f, 639.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, -970.6f, 1884.3f, 441.6f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, 4001.3f, 1727.8f, 451.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BOLT, 1131.5f, 1404.1f, 397.2f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_TURRET, 1130.0f, 1710.3f, 491.9f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_LIGHT_TRIGGER_PERMANENT, 3454.0f, 1742.7f, 135.1f, -0.00f, 3.23f, 4.22f, 2.67f, .checkpointAmbientR = 10, .checkpointAmbientG = 21, .checkpointAmbientB = 33, .checkpointDirectionalR = 255, .checkpointDirectionalG = 239, .checkpointDirectionalB = 183, .lightTriggerDirX = 0.30f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -1.00f },
{ DECO_FOGCOLOR, 3456.0f, 1749.8f, 143.0f, -0.00f, 3.62f, 4.22f, 3.50f, .fogColorR = 255, .fogColorG = 209, .fogColorB = 122 },
{ DECO_FAN2, 965.5f, 1401.5f, 450.5f, 3.14f, 0.60f, 0.60f, 0.87f },
{ DECO_CHECKPOINT, -1176.9f, 1711.2f, 409.1f, 1.10f, 1.81f, 1.15f, 2.34f },
{ DECO_BULLDOZER, 1354.0f, 1733.0f, 300.7f, -1.57f, 1.00f, 1.00f, 1.00f },
{ DECO_BULLDOZER, 894.9f, 1733.0f, 300.7f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_TURRET, -1729.6f, 1698.2f, 685.0f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_TURRET, -2123.4f, 1698.2f, 685.0f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_TURRET, -3242.4f, 1668.6f, 602.9f, 0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_FAN2, 965.5f, 1401.5f, 360.2f, 3.14f, 0.60f, 0.60f, 0.87f },
{ DECO_BOLT, -322.7f, 1380.2f, 480.9f, -0.00f, 1.00f, 1.00f, 1.00f },
{ DECO_BULLDOZER, -402.1f, 1892.6f, 515.8f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_FOGCOLOR, -6211.2f, 1749.8f, 648.7f, -0.00f, 1.98f, 4.22f, 3.50f, .fogColorR = 255, .fogColorG = 209, .fogColorB = 122 },
{ DECO_FOGCOLOR, -6370.0f, 1762.5f, 648.7f, -0.00f, 1.98f, 4.22f, 3.50f, .fogColorR = 255, .fogColorG = 44, .fogColorB = 13 },
{ DECO_LIGHT_TRIGGER_PERMANENT, -4549.6f, 1463.9f, 555.7f, -0.00f, 1.18f, 1.05f, 1.63f, .checkpointAmbientR = 10, .checkpointAmbientG = 21, .checkpointAmbientB = 33, .checkpointDirectionalR = 255, .checkpointDirectionalG = 239, .checkpointDirectionalB = 183, .lightTriggerDirX = 0.30f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -1.00f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -4664.9f, 1469.8f, 528.5f, -0.00f, 1.18f, 1.05f, 1.63f, .checkpointAmbientR = 10, .checkpointAmbientG = 22, .checkpointAmbientB = 33, .checkpointDirectionalR = 24, .checkpointDirectionalG = 33, .checkpointDirectionalB = 30, .lightTriggerDirX = 0.30f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = 0.50f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -4937.2f, 1475.6f, 516.5f, -0.00f, 1.18f, 1.05f, 1.63f, .checkpointAmbientR = 10, .checkpointAmbientG = 22, .checkpointAmbientB = 33, .checkpointDirectionalR = 24, .checkpointDirectionalG = 33, .checkpointDirectionalB = 30, .lightTriggerDirX = 0.30f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -0.50f },
{ DECO_LIGHT_TRIGGER_PERMANENT, -5054.4f, 1465.9f, 532.4f, -0.00f, 1.18f, 1.05f, 1.63f, .checkpointAmbientR = 10, .checkpointAmbientG = 21, .checkpointAmbientB = 33, .checkpointDirectionalR = 255, .checkpointDirectionalG = 239, .checkpointDirectionalB = 183, .lightTriggerDirX = 0.30f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -1.00f },
{ DECO_LIGHT_TRIGGER, -5448.2f, 1961.4f, 736.5f, -0.22f, 13.34f, 3.15f, 8.86f, .checkpointAmbientR = 10, .checkpointAmbientG = 22, .checkpointAmbientB = 33, .checkpointDirectionalR = 24, .checkpointDirectionalG = 33, .checkpointDirectionalB = 30, .lightTriggerDirX = 0.30f, .lightTriggerDirY = 1.00f, .lightTriggerDirZ = -0.50f },
{ DECO_BULLDOZER, -4848.6f, 1769.2f, 629.3f, 3.14f, 1.00f, 1.00f, 1.00f },
{ DECO_TURRET, -4504.2f, 1684.8f, 784.6f, 2.54f, 1.00f, 1.00f, 1.00f },
{ DECO_TURRET, -6054.5f, 1821.0f, 801.2f, 2.54f, 1.00f, 1.00f, 1.00f },
{ DECO_LASERWALL, -6260.6f, 1732.2f, 584.4f, -0.01f, 0.54f, 0.54f, 0.54f, .activationId = 2 },
{ DECO_DROID_SEC, 2364.4f, 1704.7f, 307.3f, 3.14f, 1.00f, 1.00f, 1.00f, .activationId = 1 },
{ DECO_DROID_SEC, -6052.3f, 1827.2f, 628.1f, 3.14f, 1.00f, 1.00f, 1.00f, .activationId = 2 },
{ DECO_BOLT, -4988.9f, 1937.5f, 704.6f, -0.00f, 1.00f, 1.00f, 1.00f },

    },
    .decorationCount = 55,

    // Player start position
    .playerStartX = 0.0f,
    .playerStartY = 100.0f,
    .playerStartZ = 0.0f,

    // Background music
    .music = "rom:/N64Chiller3.wav64",

    // Body part (1 = torso, 2 = arms)
    .bodyPart = 2,

    // Point light (optional, set hasPointLight = true to enable)
    .hasPointLight = false,
    .lightX = 0.0f,
    .lightY = 0.0f,
    .lightZ = 0.0f,

    // Directional light direction (0,0,0 = default 1,1,1 diagonal)
    // This is a vector pointing TOWARD the light source
    // Examples: (0,1,0) = noon sun, (1,0.5,0) = low side angle
    .lightDirX = -0.2f,
    .lightDirY = 0.5f,
    .lightDirZ = -1.0f,

    // Ambient light color RGB 0-255 (0,0,0 = default 80,80,80 gray)
    .ambientR = 0,
    .ambientG = 0,
    .ambientB = 0,

    // Directional light color RGB 0-255 (0,0,0 = default 255,255,255 white)
    .directionalR = 0,
    .directionalG = 0,
    .directionalB = 0,

    // Background/clear color RGB 0-255 (black default)
    .bgR = 135,
    .bgG = 206,
    .bgB = 235,

    // Fog settings - thin white/light blue atmospheric fog
    .fogEnabled = true,
    .fogR = 200,
    .fogG = 220,
    .fogB = 240,
    .fogNear = 100.0f,
    .fogFar = 600.0f,
};

#endif // LEVEL5_H
