// N64 Collision Data - Generated by Blender Export
// Model: Chargepad
// Triangles: 12

#ifndef CHARGEPAD_COLLISION_H
#define CHARGEPAD_COLLISION_H

#include "../collision.h"

static CollisionTriangle Chargepad_collision_triangles[] = {
    { -13.6f, 3.8f, 13.6f,   13.6f, 3.8f, -13.6f,   13.6f, 3.8f, 13.6f },
    { 13.6f, 3.8f, -13.6f,   24.3f, -1.3f, 24.3f,   13.6f, 3.8f, 13.6f },
    { -13.6f, 3.8f, 13.6f,   -24.3f, -1.3f, -24.3f,   -13.6f, 3.8f, -13.6f },
    { -13.6f, 3.8f, -13.6f,   24.3f, -1.3f, -24.3f,   13.6f, 3.8f, -13.6f },
    { 13.6f, 3.8f, 13.6f,   -24.3f, -1.3f, 24.3f,   -13.6f, 3.8f, 13.6f },
    { 24.3f, -1.3f, -24.3f,   -24.3f, -1.3f, 24.3f,   24.3f, -1.3f, 24.3f },
    { -13.6f, 3.8f, 13.6f,   -13.6f, 3.8f, -13.6f,   13.6f, 3.8f, -13.6f },
    { 13.6f, 3.8f, -13.6f,   24.3f, -1.3f, -24.3f,   24.3f, -1.3f, 24.3f },
    { -13.6f, 3.8f, 13.6f,   -24.3f, -1.3f, 24.3f,   -24.3f, -1.3f, -24.3f },
    { -13.6f, 3.8f, -13.6f,   -24.3f, -1.3f, -24.3f,   24.3f, -1.3f, -24.3f },
    { 13.6f, 3.8f, 13.6f,   24.3f, -1.3f, 24.3f,   -24.3f, -1.3f, 24.3f },
    { 24.3f, -1.3f, -24.3f,   -24.3f, -1.3f, -24.3f,   -24.3f, -1.3f, 24.3f },
};

static CollisionMesh Chargepad_collision = {
    .triangles = Chargepad_collision_triangles,
    .count = 12
};

#endif // CHARGEPAD_COLLISION_H
