// N64 Collision Data - Generated by Blender Export
// Model: DECO_FAN2
// Triangles: 4

#ifndef DECO_FAN2_COLLISION_H
#define DECO_FAN2_COLLISION_H

#include "../collision.h"

static CollisionTriangle DECO_FAN2_collision_triangles[] = {
    { -37.4f, -1.5f, 37.4f,   0.0f, 13.9f, -0.0f,   -37.4f, -1.5f, -37.4f },
    { -37.4f, -1.5f, -37.4f,   0.0f, 13.9f, -0.0f,   37.4f, -1.5f, -37.4f },
    { 37.4f, -1.5f, -37.4f,   0.0f, 13.9f, -0.0f,   37.4f, -1.5f, 37.4f },
    { 37.4f, -1.5f, 37.4f,   0.0f, 13.9f, -0.0f,   -37.4f, -1.5f, 37.4f },
};

static CollisionMesh DECO_FAN2_collision = {
    .triangles = DECO_FAN2_collision_triangles,
    .count = 4
};

#endif // DECO_FAN2_COLLISION_H
