// N64 Collision Data - Generated by Blender Export
// Model: RoundButtonTop
// Triangles: 24

#ifndef ROUNDBUTTONTOP_COLLISION_H
#define ROUNDBUTTONTOP_COLLISION_H

#include "../collision.h"

static CollisionTriangle RoundButtonTop_collision_triangles[] = {
    { 0.0f, 11.1f, -32.5f,   23.0f, 0.3f, -23.0f,   0.0f, 0.3f, -32.5f },
    { 23.0f, 11.1f, -23.0f,   32.5f, 0.3f, -0.0f,   23.0f, 0.3f, -23.0f },
    { 32.5f, 11.1f, -0.0f,   23.0f, 0.3f, 23.0f,   32.5f, 0.3f, -0.0f },
    { 23.0f, 11.1f, 23.0f,   0.0f, 0.3f, 32.5f,   23.0f, 0.3f, 23.0f },
    { 0.0f, 11.1f, 32.5f,   -23.0f, 0.3f, 23.0f,   0.0f, 0.3f, 32.5f },
    { -23.0f, 11.1f, 23.0f,   -32.5f, 0.3f, -0.0f,   -23.0f, 0.3f, 23.0f },
    { 32.5f, 11.1f, -0.0f,   0.0f, 16.2f, -0.0f,   23.0f, 11.1f, 23.0f },
    { -32.5f, 11.1f, -0.0f,   -23.0f, 0.3f, -23.0f,   -32.5f, 0.3f, -0.0f },
    { -23.0f, 11.1f, -23.0f,   0.0f, 0.3f, -32.5f,   -23.0f, 0.3f, -23.0f },
    { -23.0f, 11.1f, -23.0f,   0.0f, 16.2f, -0.0f,   0.0f, 11.1f, -32.5f },
    { -23.0f, 11.1f, 23.0f,   0.0f, 16.2f, -0.0f,   -32.5f, 11.1f, -0.0f },
    { 23.0f, 11.1f, -23.0f,   0.0f, 16.2f, -0.0f,   32.5f, 11.1f, -0.0f },
    { 23.0f, 11.1f, 23.0f,   0.0f, 16.2f, -0.0f,   0.0f, 11.1f, 32.5f },
    { -23.0f, 11.1f, -23.0f,   -32.5f, 11.1f, -0.0f,   0.0f, 16.2f, -0.0f },
    { 0.0f, 11.1f, 32.5f,   0.0f, 16.2f, -0.0f,   -23.0f, 11.1f, 23.0f },
    { 0.0f, 11.1f, -32.5f,   0.0f, 16.2f, -0.0f,   23.0f, 11.1f, -23.0f },
    { 0.0f, 11.1f, -32.5f,   23.0f, 11.1f, -23.0f,   23.0f, 0.3f, -23.0f },
    { 23.0f, 11.1f, -23.0f,   32.5f, 11.1f, -0.0f,   32.5f, 0.3f, -0.0f },
    { 32.5f, 11.1f, -0.0f,   23.0f, 11.1f, 23.0f,   23.0f, 0.3f, 23.0f },
    { 23.0f, 11.1f, 23.0f,   0.0f, 11.1f, 32.5f,   0.0f, 0.3f, 32.5f },
    { 0.0f, 11.1f, 32.5f,   -23.0f, 11.1f, 23.0f,   -23.0f, 0.3f, 23.0f },
    { -23.0f, 11.1f, 23.0f,   -32.5f, 11.1f, -0.0f,   -32.5f, 0.3f, -0.0f },
    { -32.5f, 11.1f, -0.0f,   -23.0f, 11.1f, -23.0f,   -23.0f, 0.3f, -23.0f },
    { -23.0f, 11.1f, -23.0f,   0.0f, 11.1f, -32.5f,   0.0f, 0.3f, -32.5f },
};

static CollisionMesh RoundButtonTop_collision = {
    .triangles = RoundButtonTop_collision_triangles,
    .count = 24
};

#endif // ROUNDBUTTONTOP_COLLISION_H
