// N64 Collision Data - Generated by Blender Export
// Model: RTurret_Base
// Triangles: 20

#ifndef RTURRET_BASE_COLLISION_H
#define RTURRET_BASE_COLLISION_H

#include "../collision.h"

static CollisionTriangle RTurret_Base_collision_triangles[] = {
    { -11.6f, 27.5f, 11.6f,   -9.2f, 12.7f, -9.2f,   -9.2f, 12.7f, 9.2f },
    { -11.6f, 27.5f, -11.6f,   9.2f, 12.7f, -9.2f,   -9.2f, 12.7f, -9.2f },
    { 11.6f, 27.5f, -11.6f,   9.2f, 12.7f, 9.2f,   9.2f, 12.7f, -9.2f },
    { 9.2f, 12.7f, 9.2f,   -11.6f, 27.5f, 11.6f,   -9.2f, 12.7f, 9.2f },
    { 11.3f, -0.1f, -11.3f,   -11.3f, -0.1f, 11.3f,   -11.3f, -0.1f, -11.3f },
    { 9.2f, 12.7f, 9.2f,   -11.3f, -0.1f, 11.3f,   11.3f, -0.1f, 11.3f },
    { 9.2f, 12.7f, -9.2f,   11.3f, -0.1f, 11.3f,   11.3f, -0.1f, -11.3f },
    { -9.2f, 12.7f, -9.2f,   11.3f, -0.1f, -11.3f,   -11.3f, -0.1f, -11.3f },
    { -9.2f, 12.7f, 9.2f,   -11.3f, -0.1f, -11.3f,   -11.3f, -0.1f, 11.3f },
    { 11.6f, 27.5f, 11.6f,   -11.6f, 27.5f, -11.6f,   -11.6f, 27.5f, 11.6f },
    { -11.6f, 27.5f, 11.6f,   -11.6f, 27.5f, -11.6f,   -9.2f, 12.7f, -9.2f },
    { -11.6f, 27.5f, -11.6f,   11.6f, 27.5f, -11.6f,   9.2f, 12.7f, -9.2f },
    { 11.6f, 27.5f, -11.6f,   11.6f, 27.5f, 11.6f,   9.2f, 12.7f, 9.2f },
    { 9.2f, 12.7f, 9.2f,   11.6f, 27.5f, 11.6f,   -11.6f, 27.5f, 11.6f },
    { 11.3f, -0.1f, -11.3f,   11.3f, -0.1f, 11.3f,   -11.3f, -0.1f, 11.3f },
    { 9.2f, 12.7f, 9.2f,   -9.2f, 12.7f, 9.2f,   -11.3f, -0.1f, 11.3f },
    { 9.2f, 12.7f, -9.2f,   9.2f, 12.7f, 9.2f,   11.3f, -0.1f, 11.3f },
    { -9.2f, 12.7f, -9.2f,   9.2f, 12.7f, -9.2f,   11.3f, -0.1f, -11.3f },
    { -9.2f, 12.7f, 9.2f,   -9.2f, 12.7f, -9.2f,   -11.3f, -0.1f, -11.3f },
    { 11.6f, 27.5f, 11.6f,   11.6f, 27.5f, -11.6f,   -11.6f, 27.5f, -11.6f },
};

static CollisionMesh RTurret_Base_collision = {
    .triangles = RTurret_Base_collision_triangles,
    .count = 20
};

#endif // RTURRET_BASE_COLLISION_H
