// N64 Collision Data - Generated by Blender Export
// Model: BlueCube
// Triangles: 12

#ifndef BLUECUBE_COLLISION_H
#define BLUECUBE_COLLISION_H

#include "../collision.h"

static CollisionTriangle BlueCube_collision_triangles[] = {
    { -64.0f, 145.8f, 64.0f,   -64.0f, 17.8f, -64.0f,   -64.0f, 17.8f, 64.0f },
    { -64.0f, 145.8f, -64.0f,   64.0f, 17.8f, -64.0f,   -64.0f, 17.8f, -64.0f },
    { 64.0f, 145.8f, -64.0f,   64.0f, 17.8f, 64.0f,   64.0f, 17.8f, -64.0f },
    { 64.0f, 145.8f, 64.0f,   -64.0f, 17.8f, 64.0f,   64.0f, 17.8f, 64.0f },
    { 64.0f, 17.8f, -64.0f,   -64.0f, 17.8f, 64.0f,   -64.0f, 17.8f, -64.0f },
    { -64.0f, 145.8f, -64.0f,   64.0f, 145.8f, 64.0f,   64.0f, 145.8f, -64.0f },
    { -64.0f, 145.8f, 64.0f,   -64.0f, 145.8f, -64.0f,   -64.0f, 17.8f, -64.0f },
    { -64.0f, 145.8f, -64.0f,   64.0f, 145.8f, -64.0f,   64.0f, 17.8f, -64.0f },
    { 64.0f, 145.8f, -64.0f,   64.0f, 145.8f, 64.0f,   64.0f, 17.8f, 64.0f },
    { 64.0f, 145.8f, 64.0f,   -64.0f, 145.8f, 64.0f,   -64.0f, 17.8f, 64.0f },
    { 64.0f, 17.8f, -64.0f,   64.0f, 17.8f, 64.0f,   -64.0f, 17.8f, 64.0f },
    { -64.0f, 145.8f, -64.0f,   -64.0f, 145.8f, 64.0f,   64.0f, 145.8f, 64.0f },
};

static CollisionMesh BlueCube_collision = {
    .triangles = BlueCube_collision_triangles,
    .count = 12
};

#endif // BLUECUBE_COLLISION_H
