// N64 Collision Data - Generated by Blender Export
// Model: bolt
// Triangles: 20

#ifndef BOLT_COLLISION_H
#define BOLT_COLLISION_H

#include "../collision.h"

// Hitbox scaled 2x for easier collection
static CollisionTriangle bolt_collision_triangles[] = {
    { -19.2f, 65.8f, 19.2f,   -48.8f, 89.4f, -48.8f,   -19.2f, 65.8f, -19.2f },
    { 19.2f, 65.8f, 19.2f,   -19.2f, 11.4f, 19.2f,   19.2f, 11.4f, 19.2f },
    { -19.2f, 65.8f, 19.2f,   -19.2f, 11.4f, -19.2f,   -19.2f, 11.4f, 19.2f },
    { 19.2f, 11.4f, -19.2f,   -19.2f, 11.4f, 19.2f,   -19.2f, 11.4f, -19.2f },
    { 19.2f, 65.8f, -19.2f,   19.2f, 11.4f, 19.2f,   19.2f, 11.4f, -19.2f },
    { -19.2f, 65.8f, -19.2f,   19.2f, 11.4f, -19.2f,   -19.2f, 11.4f, -19.2f },
    { -48.8f, 89.4f, -48.8f,   48.8f, 89.4f, 48.8f,   48.8f, 89.4f, -48.8f },
    { 19.2f, 65.8f, -19.2f,   48.8f, 89.4f, 48.8f,   19.2f, 65.8f, 19.2f },
    { -19.2f, 65.8f, -19.2f,   48.8f, 89.4f, -48.8f,   19.2f, 65.8f, -19.2f },
    { 19.2f, 65.8f, 19.2f,   -48.8f, 89.4f, 48.8f,   -19.2f, 65.8f, 19.2f },
    { -19.2f, 65.8f, 19.2f,   -48.8f, 89.4f, 48.8f,   -48.8f, 89.4f, -48.8f },
    { 19.2f, 65.8f, 19.2f,   -19.2f, 65.8f, 19.2f,   -19.2f, 11.4f, 19.2f },
    { -19.2f, 65.8f, 19.2f,   -19.2f, 65.8f, -19.2f,   -19.2f, 11.4f, -19.2f },
    { 19.2f, 11.4f, -19.2f,   19.2f, 11.4f, 19.2f,   -19.2f, 11.4f, 19.2f },
    { 19.2f, 65.8f, -19.2f,   19.2f, 65.8f, 19.2f,   19.2f, 11.4f, 19.2f },
    { -19.2f, 65.8f, -19.2f,   19.2f, 65.8f, -19.2f,   19.2f, 11.4f, -19.2f },
    { -48.8f, 89.4f, -48.8f,   -48.8f, 89.4f, 48.8f,   48.8f, 89.4f, 48.8f },
    { 19.2f, 65.8f, -19.2f,   48.8f, 89.4f, -48.8f,   48.8f, 89.4f, 48.8f },
    { -19.2f, 65.8f, -19.2f,   -48.8f, 89.4f, -48.8f,   48.8f, 89.4f, -48.8f },
    { 19.2f, 65.8f, 19.2f,   48.8f, 89.4f, 48.8f,   -48.8f, 89.4f, 48.8f },
};

static CollisionMesh bolt_collision = {
    .triangles = bolt_collision_triangles,
    .count = 20
};

#endif // BOLT_COLLISION_H
