// N64 Collision Data - Generated by Blender Export
// Model: Cliff_Hanging_Platform_S
// Triangles: 10

#ifndef CLIFF_HANGING_PLATFORM_S_COLLISION_H
#define CLIFF_HANGING_PLATFORM_S_COLLISION_H

#include "../collision.h"

static CollisionTriangle Cliff_Hanging_Platform_S_collision_triangles[] = {
    { -39.1f, 5.5f, -64.0f,   39.1f, -5.5f, -64.0f,   -39.1f, -5.5f, -64.0f },
    { 39.1f, 5.5f, 64.0f,   -39.1f, -5.5f, 64.0f,   39.1f, -5.5f, 64.0f },
    { 39.1f, 5.5f, 64.0f,   39.1f, -5.5f, -64.0f,   39.1f, 5.5f, -64.0f },
    { -39.1f, 5.5f, 64.0f,   39.1f, 5.5f, -64.0f,   -39.1f, 5.5f, -64.0f },
    { -39.1f, -5.5f, -64.0f,   -39.1f, 5.5f, 64.0f,   -39.1f, 5.5f, -64.0f },
    { -39.1f, 5.5f, -64.0f,   39.1f, 5.5f, -64.0f,   39.1f, -5.5f, -64.0f },
    { 39.1f, 5.5f, 64.0f,   -39.1f, 5.5f, 64.0f,   -39.1f, -5.5f, 64.0f },
    { 39.1f, 5.5f, 64.0f,   39.1f, -5.5f, 64.0f,   39.1f, -5.5f, -64.0f },
    { -39.1f, 5.5f, 64.0f,   39.1f, 5.5f, 64.0f,   39.1f, 5.5f, -64.0f },
    { -39.1f, -5.5f, -64.0f,   -39.1f, -5.5f, 64.0f,   -39.1f, 5.5f, 64.0f },
};

static CollisionMesh Cliff_Hanging_Platform_S_collision = {
    .triangles = Cliff_Hanging_Platform_S_collision_triangles,
    .count = 10
};

#endif // CLIFF_HANGING_PLATFORM_S_COLLISION_H
