// N64 Collision Data - Generated by Blender Export
// Model: Cliff_Hanging_Platform_L
// Triangles: 10

#ifndef CLIFF_HANGING_PLATFORM_L_COLLISION_H
#define CLIFF_HANGING_PLATFORM_L_COLLISION_H

#include "../collision.h"

static CollisionTriangle Cliff_Hanging_Platform_L_collision_triangles[] = {
    { -32.0f, 4.8f, -126.6f,   32.0f, -4.8f, -126.6f,   -32.0f, -4.8f, -126.6f },
    { 32.0f, 4.8f, 126.6f,   -32.0f, -4.8f, 126.6f,   32.0f, -4.8f, 126.6f },
    { 32.0f, 4.8f, 126.6f,   32.0f, -4.8f, -126.6f,   32.0f, 4.8f, -126.6f },
    { -32.0f, 4.8f, -126.6f,   -32.0f, -4.8f, 126.6f,   -32.0f, 4.8f, 126.6f },
    { -32.0f, 4.8f, 126.6f,   32.0f, 4.8f, -126.6f,   -32.0f, 4.8f, -126.6f },
    { -32.0f, 4.8f, -126.6f,   32.0f, 4.8f, -126.6f,   32.0f, -4.8f, -126.6f },
    { 32.0f, 4.8f, 126.6f,   -32.0f, 4.8f, 126.6f,   -32.0f, -4.8f, 126.6f },
    { 32.0f, 4.8f, 126.6f,   32.0f, -4.8f, 126.6f,   32.0f, -4.8f, -126.6f },
    { -32.0f, 4.8f, -126.6f,   -32.0f, -4.8f, -126.6f,   -32.0f, -4.8f, 126.6f },
    { -32.0f, 4.8f, 126.6f,   32.0f, 4.8f, 126.6f,   32.0f, 4.8f, -126.6f },
};

static CollisionMesh Cliff_Hanging_Platform_L_collision = {
    .triangles = Cliff_Hanging_Platform_L_collision_triangles,
    .count = 10
};

#endif // CLIFF_HANGING_PLATFORM_L_COLLISION_H
