// N64 Collision Data - Generated by Blender Export
// Model: ConveyerLargeBelt
// Triangles: 20

#ifndef CONVEYERLARGEBELT_COLLISION_H
#define CONVEYERLARGEBELT_COLLISION_H

#include "../collision.h"

static CollisionTriangle ConveyerLargeBelt_collision_triangles[] = {
    { -160.0f, -0.1f, 38.6f,   0.0f, -0.1f, -38.6f,   0.0f, -0.1f, 38.6f },
    { 160.0f, 12.7f, 38.6f,   164.1f, 10.0f, -38.6f,   160.0f, 12.7f, -38.6f },
    { 160.0f, -0.1f, -38.6f,   164.1f, 2.7f, 38.6f,   160.0f, -0.1f, 38.6f },
    { 164.1f, 2.7f, -38.6f,   164.1f, 10.0f, 38.6f,   164.1f, 2.7f, 38.6f },
    { 160.0f, 12.7f, -38.6f,   0.0f, 12.7f, 38.6f,   160.0f, 12.7f, 38.6f },
    { -164.1f, 10.0f, -38.6f,   -160.0f, 12.7f, 38.6f,   -160.0f, 12.7f, -38.6f },
    { -164.1f, 2.7f, 38.6f,   -160.0f, -0.1f, -38.6f,   -160.0f, -0.1f, 38.6f },
    { -164.1f, 10.0f, 38.6f,   -164.1f, 2.7f, -38.6f,   -164.1f, 2.7f, 38.6f },
    { 0.0f, 12.7f, 38.6f,   -160.0f, 12.7f, -38.6f,   -160.0f, 12.7f, 38.6f },
    { 0.0f, -0.1f, -38.6f,   160.0f, -0.1f, 38.6f,   0.0f, -0.1f, 38.6f },
    { -160.0f, -0.1f, 38.6f,   -160.0f, -0.1f, -38.6f,   0.0f, -0.1f, -38.6f },
    { 160.0f, 12.7f, 38.6f,   164.1f, 10.0f, 38.6f,   164.1f, 10.0f, -38.6f },
    { 160.0f, -0.1f, -38.6f,   164.1f, 2.7f, -38.6f,   164.1f, 2.7f, 38.6f },
    { 164.1f, 2.7f, -38.6f,   164.1f, 10.0f, -38.6f,   164.1f, 10.0f, 38.6f },
    { 160.0f, 12.7f, -38.6f,   0.0f, 12.7f, -38.6f,   0.0f, 12.7f, 38.6f },
    { -164.1f, 10.0f, -38.6f,   -164.1f, 10.0f, 38.6f,   -160.0f, 12.7f, 38.6f },
    { -164.1f, 2.7f, 38.6f,   -164.1f, 2.7f, -38.6f,   -160.0f, -0.1f, -38.6f },
    { -164.1f, 10.0f, 38.6f,   -164.1f, 10.0f, -38.6f,   -164.1f, 2.7f, -38.6f },
    { 0.0f, 12.7f, 38.6f,   0.0f, 12.7f, -38.6f,   -160.0f, 12.7f, -38.6f },
    { 0.0f, -0.1f, -38.6f,   160.0f, -0.1f, -38.6f,   160.0f, -0.1f, 38.6f },
};

static CollisionMesh ConveyerLargeBelt_collision = {
    .triangles = ConveyerLargeBelt_collision_triangles,
    .count = 20
};

#endif // CONVEYERLARGEBELT_COLLISION_H
