// N64 Collision Data - Generated by Blender Export
// Model: DamageCollision
// Triangles: 12

#ifndef DAMAGECOLLISION_COLLISION_H
#define DAMAGECOLLISION_COLLISION_H

#include "../collision.h"

static CollisionTriangle DamageCollision_collision_triangles[] = {
    { -64.0f, 64.0f, -64.0f,   64.0f, 64.0f, 64.0f,   64.0f, 64.0f, -64.0f },
    { 64.0f, 64.0f, 64.0f,   -64.0f, -64.0f, 64.0f,   64.0f, -64.0f, 64.0f },
    { -64.0f, 64.0f, 64.0f,   -64.0f, -64.0f, -64.0f,   -64.0f, -64.0f, 64.0f },
    { 64.0f, -64.0f, -64.0f,   -64.0f, -64.0f, 64.0f,   -64.0f, -64.0f, -64.0f },
    { 64.0f, 64.0f, -64.0f,   64.0f, -64.0f, 64.0f,   64.0f, -64.0f, -64.0f },
    { -64.0f, 64.0f, -64.0f,   64.0f, -64.0f, -64.0f,   -64.0f, -64.0f, -64.0f },
    { -64.0f, 64.0f, -64.0f,   -64.0f, 64.0f, 64.0f,   64.0f, 64.0f, 64.0f },
    { 64.0f, 64.0f, 64.0f,   -64.0f, 64.0f, 64.0f,   -64.0f, -64.0f, 64.0f },
    { -64.0f, 64.0f, 64.0f,   -64.0f, 64.0f, -64.0f,   -64.0f, -64.0f, -64.0f },
    { 64.0f, -64.0f, -64.0f,   64.0f, -64.0f, 64.0f,   -64.0f, -64.0f, 64.0f },
    { 64.0f, 64.0f, -64.0f,   64.0f, 64.0f, 64.0f,   64.0f, -64.0f, 64.0f },
    { -64.0f, 64.0f, -64.0f,   64.0f, 64.0f, -64.0f,   64.0f, -64.0f, -64.0f },
};

static CollisionMesh DamageCollision_collision = {
    .triangles = DamageCollision_collision_triangles,
    .count = 12
};

#endif // DAMAGECOLLISION_COLLISION_H
