// N64 Collision Data - Generated by Blender Export
// Model: DECO_FAN2
// Triangles: 6

#ifndef DECO_FAN2_COLLISION_H
#define DECO_FAN2_COLLISION_H

#include "../collision.h"

static CollisionTriangle DECO_FAN2_collision_triangles[] = {
    { -32.0f, -0.6f, 32.0f,   0.0f, 118.1f, -0.0f,   -32.0f, -0.6f, -32.0f },
    { -32.0f, -0.6f, -32.0f,   0.0f, 118.1f, -0.0f,   32.0f, -0.6f, -32.0f },
    { 32.0f, -0.6f, -32.0f,   0.0f, 118.1f, -0.0f,   32.0f, -0.6f, 32.0f },
    { 32.0f, -0.6f, 32.0f,   0.0f, 118.1f, -0.0f,   -32.0f, -0.6f, 32.0f },
    { 32.0f, -0.6f, -32.0f,   -32.0f, -0.6f, 32.0f,   -32.0f, -0.6f, -32.0f },
    { 32.0f, -0.6f, -32.0f,   32.0f, -0.6f, 32.0f,   -32.0f, -0.6f, 32.0f },
};

static CollisionMesh DECO_FAN2_collision = {
    .triangles = DECO_FAN2_collision_triangles,
    .count = 6
};

#endif // DECO_FAN2_COLLISION_H
