// N64 Collision Data - Generated by Blender Export
// Model: Elevator
// Triangles: 12

#ifndef ELEVATOR_COLLISION_H
#define ELEVATOR_COLLISION_H

#include "../collision.h"

static CollisionTriangle Elevator_collision_triangles[] = {
    { -133.8f, 39.9f, -133.8f,   133.8f, 39.9f, 133.8f,   133.8f, 39.9f, -133.8f },
    { 133.8f, 39.9f, 133.8f,   -133.8f, 15.4f, 133.8f,   133.8f, 15.4f, 133.8f },
    { -133.8f, 39.9f, 133.8f,   -133.8f, 15.4f, -133.8f,   -133.8f, 15.4f, 133.8f },
    { 133.8f, 15.4f, -133.8f,   -133.8f, 15.4f, 133.8f,   -133.8f, 15.4f, -133.8f },
    { 133.8f, 39.9f, -133.8f,   133.8f, 15.4f, 133.8f,   133.8f, 15.4f, -133.8f },
    { -133.8f, 39.9f, -133.8f,   133.8f, 15.4f, -133.8f,   -133.8f, 15.4f, -133.8f },
    { -133.8f, 39.9f, -133.8f,   -133.8f, 39.9f, 133.8f,   133.8f, 39.9f, 133.8f },
    { 133.8f, 39.9f, 133.8f,   -133.8f, 39.9f, 133.8f,   -133.8f, 15.4f, 133.8f },
    { -133.8f, 39.9f, 133.8f,   -133.8f, 39.9f, -133.8f,   -133.8f, 15.4f, -133.8f },
    { 133.8f, 15.4f, -133.8f,   133.8f, 15.4f, 133.8f,   -133.8f, 15.4f, 133.8f },
    { 133.8f, 39.9f, -133.8f,   133.8f, 39.9f, 133.8f,   133.8f, 15.4f, 133.8f },
    { -133.8f, 39.9f, -133.8f,   133.8f, 39.9f, -133.8f,   133.8f, 15.4f, -133.8f },
};

static CollisionMesh Elevator_collision = {
    .triangles = Elevator_collision_triangles,
    .count = 12
};

#endif // ELEVATOR_COLLISION_H
