// N64 Collision Data - Generated by Blender Export
// Model: level3_water_level
// Triangles: 18

#ifndef LEVEL3_WATER_LEVEL_COLLISION_H
#define LEVEL3_WATER_LEVEL_COLLISION_H

#include "../collision.h"

static CollisionTriangle level3_water_level_collision_triangles[] = {
    { 4239.9f, -7.3f, 482.4f,   4905.6f, -7.3f, -435.5f,   4263.7f, -7.3f, -657.9f },
    { -1181.6f, -7.3f, 482.4f,   -535.7f, -7.3f, -618.2f,   -1157.8f, -7.3f, -626.2f },
    { -504.0f, -7.3f, 482.4f,   157.8f, -7.3f, -244.9f,   -535.7f, -7.3f, -618.2f },
    { 173.7f, -7.3f, 482.4f,   799.8f, -7.3f, -181.4f,   157.8f, -7.3f, -244.9f },
    { 851.4f, -7.3f, 482.4f,   1497.3f, -7.3f, -169.5f,   799.8f, -7.3f, -181.4f },
    { 1529.1f, -7.3f, 482.4f,   2171.1f, -7.3f, 13.2f,   1497.3f, -7.3f, -169.5f },
    { 2884.5f, -7.3f, 482.4f,   2171.1f, -7.3f, 13.2f,   2206.8f, -7.3f, 482.4f },
    { 2884.5f, -7.3f, 482.4f,   3566.1f, -7.3f, -800.9f,   2908.3f, -7.3f, -931.9f },
    { 3562.2f, -7.3f, 482.4f,   4263.7f, -7.3f, -657.9f,   3566.1f, -7.3f, -800.9f },
    { 4239.9f, -7.3f, 482.4f,   4917.6f, -7.3f, 482.4f,   4905.6f, -7.3f, -435.5f },
    { -1181.6f, -7.3f, 482.4f,   -504.0f, -7.3f, 482.4f,   -535.7f, -7.3f, -618.2f },
    { -504.0f, -7.3f, 482.4f,   173.7f, -7.3f, 482.4f,   157.8f, -7.3f, -244.9f },
    { 173.7f, -7.3f, 482.4f,   851.4f, -7.3f, 482.4f,   799.8f, -7.3f, -181.4f },
    { 851.4f, -7.3f, 482.4f,   1529.1f, -7.3f, 482.4f,   1497.3f, -7.3f, -169.5f },
    { 1529.1f, -7.3f, 482.4f,   2206.8f, -7.3f, 482.4f,   2171.1f, -7.3f, 13.2f },
    { 2884.5f, -7.3f, 482.4f,   2908.3f, -7.3f, -931.9f,   2171.1f, -7.3f, 13.2f },
    { 2884.5f, -7.3f, 482.4f,   3562.2f, -7.3f, 482.4f,   3566.1f, -7.3f, -800.9f },
    { 3562.2f, -7.3f, 482.4f,   4239.9f, -7.3f, 482.4f,   4263.7f, -7.3f, -657.9f },
};

static CollisionMesh level3_water_level_collision = {
    .triangles = level3_water_level_collision_triangles,
    .count = 18
};

#endif // LEVEL3_WATER_LEVEL_COLLISION_H
