// N64 Collision Chunk Index - Auto-generated by chunk_collision.py
// Model: level1
// Chunks: 5

#ifndef LEVEL1_CHUNKS_H
#define LEVEL1_CHUNKS_H

#define LEVEL1_CHUNK_COUNT 5
static const char* level1_chunks[] = { "level1_chunk0", "level1_chunk1", "level1_chunk2", "level1_chunk3", "level1_chunk4" };

#endif // LEVEL1_CHUNKS_H
