// N64 Collision Chunk Index - Auto-generated by chunk_collision.py
// Model: level3
// Chunks: 22

#ifndef LEVEL3_CHUNKS_H
#define LEVEL3_CHUNKS_H

#define LEVEL3_CHUNK_COUNT 22
static const char* level3_chunks[] = { "level3_chunk0", "level3_chunk1", "level3_chunk2", "level3_chunk3", "level3_chunk4", "level3_chunk5", "level3_chunk6", "level3_chunk7", "level3_chunk8", "level3_chunk9", "level3_chunk10", "level3_chunk11", "level3_chunk12", "level3_chunk13", "level3_chunk14", "level3_chunk15", "level3_chunk16", "level3_chunk17", "level3_chunk18", "level3_chunk19", "level3_chunk20", "level3_chunk21" };

#endif // LEVEL3_CHUNKS_H
