// N64 Collision Data - Generated by Blender Export
// Model: MonitorScreen
// Triangles: 10

#ifndef MONITORSCREEN_COLLISION_H
#define MONITORSCREEN_COLLISION_H

#include "../collision.h"

static CollisionTriangle MonitorScreen_collision_triangles[] = {
    { 1.1f, 35.6f, 3.7f,   1.1f, 58.0f, 3.7f,   -0.1f, 56.3f, 2.1f },
    { 1.1f, 35.6f, 3.7f,   -0.1f, 56.3f, 2.1f,   -0.1f, 37.3f, 2.1f },
    { -0.1f, 37.3f, 2.1f,   -0.1f, 56.3f, 2.1f,   -3.8f, 56.3f, -16.5f },
    { -0.1f, 37.3f, 2.1f,   -3.8f, 56.3f, -16.5f,   -3.8f, 37.3f, -16.5f },
    { 1.1f, 58.0f, 3.7f,   -3.2f, 58.0f, -18.4f,   -3.8f, 56.3f, -16.5f },
    { 1.1f, 58.0f, 3.7f,   -3.8f, 56.3f, -16.5f,   -0.1f, 56.3f, 2.1f },
    { -3.2f, 35.6f, -18.4f,   1.1f, 35.6f, 3.7f,   -0.1f, 37.3f, 2.1f },
    { -3.2f, 35.6f, -18.4f,   -0.1f, 37.3f, 2.1f,   -3.8f, 37.3f, -16.5f },
    { -3.2f, 58.0f, -18.4f,   -3.2f, 35.6f, -18.4f,   -3.8f, 37.3f, -16.5f },
    { -3.2f, 58.0f, -18.4f,   -3.8f, 37.3f, -16.5f,   -3.8f, 56.3f, -16.5f },
};

static CollisionMesh MonitorScreen_collision = {
    .triangles = MonitorScreen_collision_triangles,
    .count = 10
};

#endif // MONITORSCREEN_COLLISION_H
