// N64 Collision Data - Generated by Blender Export
// Model: PatrolPoint
// Triangles: 12

#ifndef PATROLPOINT_COLLISION_H
#define PATROLPOINT_COLLISION_H

#include "../collision.h"

static CollisionTriangle PatrolPoint_collision_triangles[] = {
    { -6.4f, 22.8f, 6.4f,   -6.4f, 10.0f, -6.4f,   -6.4f, 10.0f, 6.4f },
    { -6.4f, 22.8f, -6.4f,   6.4f, 10.0f, -6.4f,   -6.4f, 10.0f, -6.4f },
    { 6.4f, 22.8f, -6.4f,   6.4f, 10.0f, 6.4f,   6.4f, 10.0f, -6.4f },
    { 6.4f, 22.8f, 6.4f,   -6.4f, 10.0f, 6.4f,   6.4f, 10.0f, 6.4f },
    { 6.4f, 10.0f, -6.4f,   -6.4f, 10.0f, 6.4f,   -6.4f, 10.0f, -6.4f },
    { -6.4f, 22.8f, -6.4f,   6.4f, 22.8f, 6.4f,   6.4f, 22.8f, -6.4f },
    { -6.4f, 22.8f, 6.4f,   -6.4f, 22.8f, -6.4f,   -6.4f, 10.0f, -6.4f },
    { -6.4f, 22.8f, -6.4f,   6.4f, 22.8f, -6.4f,   6.4f, 10.0f, -6.4f },
    { 6.4f, 22.8f, -6.4f,   6.4f, 22.8f, 6.4f,   6.4f, 10.0f, 6.4f },
    { 6.4f, 22.8f, 6.4f,   -6.4f, 22.8f, 6.4f,   -6.4f, 10.0f, 6.4f },
    { 6.4f, 10.0f, -6.4f,   6.4f, 10.0f, 6.4f,   -6.4f, 10.0f, 6.4f },
    { -6.4f, 22.8f, -6.4f,   -6.4f, 22.8f, 6.4f,   6.4f, 22.8f, 6.4f },
};

static CollisionMesh PatrolPoint_collision = {
    .triangles = PatrolPoint_collision_triangles,
    .count = 12
};

#endif // PATROLPOINT_COLLISION_H
