// N64 Collision Data - Generated by Blender Export
// Model: Platform
// Triangles: 12

#ifndef PLATFORM_COLLISION_H
#define PLATFORM_COLLISION_H

#include "../collision.h"

static CollisionTriangle Platform_collision_triangles[] = {
    { 193.5f, 707.9f, 803.9f,   4.3f, 707.9f, 592.4f,   193.5f, 707.9f, 592.4f },
    { 4.3f, 707.9f, 592.4f,   193.5f, 742.8f, 592.4f,   193.5f, 707.9f, 592.4f },
    { 193.5f, 707.9f, 803.9f,   4.3f, 742.8f, 803.9f,   4.3f, 707.9f, 803.9f },
    { 193.5f, 742.8f, 592.4f,   193.5f, 707.9f, 803.9f,   193.5f, 707.9f, 592.4f },
    { 4.3f, 742.8f, 803.9f,   4.3f, 707.9f, 592.4f,   4.3f, 707.9f, 803.9f },
    { 4.3f, 742.8f, 803.9f,   193.5f, 742.8f, 592.4f,   4.3f, 742.8f, 592.4f },
    { 193.5f, 707.9f, 803.9f,   4.3f, 707.9f, 803.9f,   4.3f, 707.9f, 592.4f },
    { 4.3f, 707.9f, 592.4f,   4.3f, 742.8f, 592.4f,   193.5f, 742.8f, 592.4f },
    { 193.5f, 707.9f, 803.9f,   193.5f, 742.8f, 803.9f,   4.3f, 742.8f, 803.9f },
    { 193.5f, 742.8f, 592.4f,   193.5f, 742.8f, 803.9f,   193.5f, 707.9f, 803.9f },
    { 4.3f, 742.8f, 803.9f,   4.3f, 742.8f, 592.4f,   4.3f, 707.9f, 592.4f },
    { 4.3f, 742.8f, 803.9f,   193.5f, 742.8f, 803.9f,   193.5f, 742.8f, 592.4f },
};

static CollisionMesh Platform_collision = {
    .triangles = Platform_collision_triangles,
    .count = 12
};

#endif // PLATFORM_COLLISION_H
