// N64 Collision Data - Generated by Blender Export
// Model: spikes_c
// Triangles: 12

#ifndef SPIKES_C_COLLISION_H
#define SPIKES_C_COLLISION_H

#include "../collision.h"

static CollisionTriangle spikes_c_collision_triangles[] = {
    { -29.0f, 39.2f, 29.0f,   -29.0f, -1.5f, -29.0f,   -29.0f, -1.5f, 29.0f },
    { -29.0f, 39.2f, -29.0f,   29.0f, -1.5f, -29.0f,   -29.0f, -1.5f, -29.0f },
    { 29.0f, 39.2f, -29.0f,   29.0f, -1.5f, 29.0f,   29.0f, -1.5f, -29.0f },
    { 29.0f, 39.2f, 29.0f,   -29.0f, -1.5f, 29.0f,   29.0f, -1.5f, 29.0f },
    { 29.0f, -1.5f, -29.0f,   -29.0f, -1.5f, 29.0f,   -29.0f, -1.5f, -29.0f },
    { -29.0f, 39.2f, -29.0f,   29.0f, 39.2f, 29.0f,   29.0f, 39.2f, -29.0f },
    { -29.0f, 39.2f, 29.0f,   -29.0f, 39.2f, -29.0f,   -29.0f, -1.5f, -29.0f },
    { -29.0f, 39.2f, -29.0f,   29.0f, 39.2f, -29.0f,   29.0f, -1.5f, -29.0f },
    { 29.0f, 39.2f, -29.0f,   29.0f, 39.2f, 29.0f,   29.0f, -1.5f, 29.0f },
    { 29.0f, 39.2f, 29.0f,   -29.0f, 39.2f, 29.0f,   -29.0f, -1.5f, 29.0f },
    { 29.0f, -1.5f, -29.0f,   29.0f, -1.5f, 29.0f,   -29.0f, -1.5f, 29.0f },
    { -29.0f, 39.2f, -29.0f,   -29.0f, 39.2f, 29.0f,   29.0f, 39.2f, 29.0f },
};

static CollisionMesh spikes_c_collision = {
    .triangles = spikes_c_collision_triangles,
    .count = 12
};

#endif // SPIKES_C_COLLISION_H
