// N64 Collision Data - Generated by Blender Export
// Model: spikes
// Triangles: 12

#ifndef SPIKES_COLLISION_H
#define SPIKES_COLLISION_H

#include "../collision.h"

static CollisionTriangle spikes_collision_triangles[] = {
    { -29.0f, 39.2f, 29.0f,   -29.0f, -1.5f, -29.0f,   -29.0f, -1.5f, 29.0f },
    { -29.0f, 39.2f, -29.0f,   29.0f, -1.5f, -29.0f,   -29.0f, -1.5f, -29.0f },
    { 29.0f, 39.2f, -29.0f,   29.0f, -1.5f, 29.0f,   29.0f, -1.5f, -29.0f },
    { 29.0f, 39.2f, 29.0f,   -29.0f, -1.5f, 29.0f,   29.0f, -1.5f, 29.0f },
    { 29.0f, -1.5f, -29.0f,   -29.0f, -1.5f, 29.0f,   -29.0f, -1.5f, -29.0f },
    { -29.0f, 39.2f, -29.0f,   29.0f, 39.2f, 29.0f,   29.0f, 39.2f, -29.0f },
    { -29.0f, 39.2f, 29.0f,   -29.0f, 39.2f, -29.0f,   -29.0f, -1.5f, -29.0f },
    { -29.0f, 39.2f, -29.0f,   29.0f, 39.2f, -29.0f,   29.0f, -1.5f, -29.0f },
    { 29.0f, 39.2f, -29.0f,   29.0f, 39.2f, 29.0f,   29.0f, -1.5f, 29.0f },
    { 29.0f, 39.2f, 29.0f,   -29.0f, 39.2f, 29.0f,   -29.0f, -1.5f, 29.0f },
    { 29.0f, -1.5f, -29.0f,   29.0f, -1.5f, 29.0f,   -29.0f, -1.5f, 29.0f },
    { -29.0f, 39.2f, -29.0f,   -29.0f, 39.2f, 29.0f,   29.0f, 39.2f, 29.0f },
};

static CollisionMesh spikes_collision = {
    .triangles = spikes_collision_triangles,
    .count = 12
};

#endif // SPIKES_COLLISION_H
