// N64 Collision Data - Generated by Blender Export
// Model: Toxic_Level2_Running
// Triangles: 24

#ifndef TOXIC_LEVEL2_RUNNING_COLLISION_H
#define TOXIC_LEVEL2_RUNNING_COLLISION_H

#include "../collision.h"

static CollisionTriangle Toxic_Level2_Running_collision_triangles[] = {
    { 36.9f, 15.7f, 55.0f,   -9.4f, 15.7f, -63.1f,   2.0f, 15.7f, 56.7f },
    { 4.0f, 1.4f, 144.7f,   33.4f, -11.8f, 139.4f,   36.6f, 1.4f, 136.2f },
    { 2.0f, 15.7f, 56.7f,   32.1f, 11.9f, 129.0f,   36.9f, 15.7f, 55.0f },
    { 3.6f, -11.8f, 148.8f,   33.0f, -45.3f, 139.0f,   33.4f, -11.8f, 139.4f },
    { -9.4f, 15.7f, -63.1f,   48.7f, 15.7f, -94.5f,   -13.6f, 15.7f, -117.1f },
    { -9.4f, 15.7f, -63.1f,   -64.0f, 15.7f, -93.5f,   -60.5f, 15.7f, -62.3f },
    { -26.2f, -11.8f, 158.3f,   3.6f, -45.3f, 149.2f,   3.6f, -11.8f, 148.8f },
    { -32.9f, 15.7f, 58.3f,   3.6f, 11.9f, 135.3f,   2.0f, 15.7f, 56.7f },
    { -28.6f, 1.4f, 153.2f,   3.6f, -11.8f, 148.8f,   4.0f, 1.4f, 144.7f },
    { -32.9f, 15.7f, 58.3f,   -9.4f, 15.7f, -63.1f,   -60.5f, 15.7f, -62.3f },
    { -24.9f, 11.9f, 141.6f,   4.0f, 1.4f, 144.7f,   3.6f, 11.9f, 135.3f },
    { 4.0f, 1.4f, 144.7f,   32.1f, 11.9f, 129.0f,   3.6f, 11.9f, 135.3f },
    { 36.9f, 15.7f, 55.0f,   41.6f, 15.7f, -63.9f,   -9.4f, 15.7f, -63.1f },
    { 4.0f, 1.4f, 144.7f,   3.6f, -11.8f, 148.8f,   33.4f, -11.8f, 139.4f },
    { 2.0f, 15.7f, 56.7f,   3.6f, 11.9f, 135.3f,   32.1f, 11.9f, 129.0f },
    { 3.6f, -11.8f, 148.8f,   3.6f, -45.3f, 149.2f,   33.0f, -45.3f, 139.0f },
    { -9.4f, 15.7f, -63.1f,   41.6f, 15.7f, -63.9f,   48.7f, 15.7f, -94.5f },
    { -9.4f, 15.7f, -63.1f,   -13.6f, 15.7f, -117.1f,   -64.0f, 15.7f, -93.5f },
    { -26.2f, -11.8f, 158.3f,   -25.8f, -45.3f, 159.5f,   3.6f, -45.3f, 149.2f },
    { -32.9f, 15.7f, 58.3f,   -24.9f, 11.9f, 141.6f,   3.6f, 11.9f, 135.3f },
    { -28.6f, 1.4f, 153.2f,   -26.2f, -11.8f, 158.3f,   3.6f, -11.8f, 148.8f },
    { -32.9f, 15.7f, 58.3f,   2.0f, 15.7f, 56.7f,   -9.4f, 15.7f, -63.1f },
    { -24.9f, 11.9f, 141.6f,   -28.6f, 1.4f, 153.2f,   4.0f, 1.4f, 144.7f },
    { 4.0f, 1.4f, 144.7f,   36.6f, 1.4f, 136.2f,   32.1f, 11.9f, 129.0f },
};

static CollisionMesh Toxic_Level2_Running_collision = {
    .triangles = Toxic_Level2_Running_collision_triangles,
    .count = 24
};

#endif // TOXIC_LEVEL2_RUNNING_COLLISION_H
