// N64 Collision Data - Generated by Blender Export
// Model: Toxic_Level2_Running
// Triangles: 19

#ifndef TOXIC_LEVEL2_RUNNING_COLLISION_H
#define TOXIC_LEVEL2_RUNNING_COLLISION_H

#include "../collision.h"

static CollisionTriangle Toxic_Level2_Running_collision_triangles[] = {
    { 9.2f, 2.2f, 33.0f,   -0.0f, 6.6f, 31.3f,   0.8f, -0.1f, 36.5f },
    { -9.0f, -9.5f, 32.3f,   0.5f, -24.5f, 38.7f,   0.5f, -9.1f, 38.7f },
    { 0.5f, -9.1f, 38.7f,   9.0f, -24.3f, 32.3f,   9.0f, -8.2f, 32.3f },
    { -8.8f, 1.5f, 33.0f,   -0.0f, 6.6f, 31.3f,   -9.0f, 10.2f, 32.3f },
    { -9.0f, -9.5f, 32.3f,   0.8f, -0.1f, 36.5f,   -8.8f, 1.5f, 33.0f },
    { 9.0f, -8.2f, 32.3f,   0.8f, -0.1f, 36.5f,   0.5f, -9.1f, 38.7f },
    { -8.8f, 1.5f, 33.0f,   9.0f, -8.2f, 32.3f,   -9.0f, -9.5f, 32.3f },
    { -9.0f, -9.5f, 32.3f,   9.0f, -24.3f, 32.3f,   -9.0f, -24.3f, 32.3f },
    { 0.5f, -24.5f, 38.7f,   -9.0f, -24.3f, 32.3f,   9.0f, -24.3f, 32.3f },
    { 9.0f, 10.2f, 32.3f,   -8.8f, 1.5f, 33.0f,   -9.0f, 10.2f, 32.3f },
    { 9.2f, 2.2f, 33.0f,   9.0f, 10.2f, 32.3f,   -0.0f, 6.6f, 31.3f },
    { -9.0f, -9.5f, 32.3f,   -9.0f, -24.3f, 32.3f,   0.5f, -24.5f, 38.7f },
    { 0.5f, -9.1f, 38.7f,   0.5f, -24.5f, 38.7f,   9.0f, -24.3f, 32.3f },
    { -8.8f, 1.5f, 33.0f,   0.8f, -0.1f, 36.5f,   -0.0f, 6.6f, 31.3f },
    { -9.0f, -9.5f, 32.3f,   0.5f, -9.1f, 38.7f,   0.8f, -0.1f, 36.5f },
    { 9.0f, -8.2f, 32.3f,   9.2f, 2.2f, 33.0f,   0.8f, -0.1f, 36.5f },
    { -8.8f, 1.5f, 33.0f,   9.2f, 2.2f, 33.0f,   9.0f, -8.2f, 32.3f },
    { -9.0f, -9.5f, 32.3f,   9.0f, -8.2f, 32.3f,   9.0f, -24.3f, 32.3f },
    { 9.0f, 10.2f, 32.3f,   9.2f, 2.2f, 33.0f,   -8.8f, 1.5f, 33.0f },
};

static CollisionMesh Toxic_Level2_Running_collision = {
    .triangles = Toxic_Level2_Running_collision_triangles,
    .count = 19
};

#endif // TOXIC_LEVEL2_RUNNING_COLLISION_H
