// N64 Collision Data - Generated by Blender Export
// Model: TransitionCollision
// Triangles: 12

#ifndef TRANSITIONCOLLISION_COLLISION_H
#define TRANSITIONCOLLISION_COLLISION_H

#include "../collision.h"

static CollisionTriangle TransitionCollision_collision_triangles[] = {
    { -64.0f, 64.0f, -64.0f,   64.0f, 64.0f, 64.0f,   64.0f, 64.0f, -64.0f },
    { 64.0f, 64.0f, 64.0f,   -64.0f, -64.0f, 64.0f,   64.0f, -64.0f, 64.0f },
    { -64.0f, 64.0f, 64.0f,   -64.0f, -64.0f, -64.0f,   -64.0f, -64.0f, 64.0f },
    { 64.0f, -64.0f, -64.0f,   -64.0f, -64.0f, 64.0f,   -64.0f, -64.0f, -64.0f },
    { 64.0f, 64.0f, -64.0f,   64.0f, -64.0f, 64.0f,   64.0f, -64.0f, -64.0f },
    { -64.0f, 64.0f, -64.0f,   64.0f, -64.0f, -64.0f,   -64.0f, -64.0f, -64.0f },
    { -64.0f, 64.0f, -64.0f,   -64.0f, 64.0f, 64.0f,   64.0f, 64.0f, 64.0f },
    { 64.0f, 64.0f, 64.0f,   -64.0f, 64.0f, 64.0f,   -64.0f, -64.0f, 64.0f },
    { -64.0f, 64.0f, 64.0f,   -64.0f, 64.0f, -64.0f,   -64.0f, -64.0f, -64.0f },
    { 64.0f, -64.0f, -64.0f,   64.0f, -64.0f, 64.0f,   -64.0f, -64.0f, 64.0f },
    { 64.0f, 64.0f, -64.0f,   64.0f, 64.0f, 64.0f,   64.0f, -64.0f, 64.0f },
    { -64.0f, 64.0f, -64.0f,   64.0f, 64.0f, -64.0f,   64.0f, -64.0f, -64.0f },
};

static CollisionMesh TransitionCollision_collision = {
    .triangles = TransitionCollision_collision_triangles,
    .count = 12
};

#endif // TRANSITIONCOLLISION_COLLISION_H
