#ifndef COLLISION_REGISTRY_H
#define COLLISION_REGISTRY_H

/**
 * Collision Registry - Runtime Loading Version
 *
 * All collision data is loaded from ROM (.col files) at runtime.
 * This keeps the ELF small and allows for larger collision data.
 *
 * Generated by tools/generate_collision_registry.py
 */

#include "collision.h"
#include "collision_loader.h"
#include <string.h>

// ============================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// ============================================================

// All collision mesh names (for reference/debugging)
// Suppress unused warning - kept for debug introspection
__attribute__((unused))
static const char* collision_names[] = {
    "Arms_playground",
    "Arms_playground_grab",
    "Arms_playground_hang",
    "BlueCube",
    "Bulldozer",
    "Cactus",
    "Chargepad",
    "Cliff_Hanging_Platform_L",
    "Cliff_Hanging_Platform_S",
    "ConveyerLargeBelt",
    "ConveyerLargeFrame",
    "ConveyerLarge",
    "DECO_FAN2",
    "DECO_GRINDER",
    "DECO_MOVING_LASER",
    "DamageCollision",
    "Elevator",
    "FanBody",
    "FanBottom",
    "Ibeam",
    "JukeBox",
    "LaserWallOff",
    "LaserWall",
    "MenuScene",
    "MonitorScreen",
    "PatrolPoint",
    "Platform",
    "Rock",
    "RoundButtonBottom",
    "RoundButtonTop",
    "Screw",
    "Sign",
    "Table",
    "Toxic_Level2_Pipe",
    "Toxic_Level2_Running",
    "TransitionCollision",
    "barrel",
    "bolt",
    "cog",
    "level1",
    "level2_chunk0",
    "level2_chunk10",
    "level2_chunk11",
    "level2_chunk12",
    "level2_chunk1",
    "level2_chunk2",
    "level2_chunk3",
    "level2_chunk4",
    "level2_chunk5",
    "level2_chunk6",
    "level2_chunk7",
    "level2_chunk8",
    "level2_chunk9",
    "level2",
    "level3_chunk0",
    "level3_chunk1",
    "level3_chunk2",
    "level3_chunk3",
    "level3_chunk4",
    "level3_chunk5",
    "level3_chunk6",
    "level3_chunk7",
    "level3",
    "level3_water_level",
    "level4_chunk0",
    "level4_chunk10",
    "level4_chunk11",
    "level4_chunk12",
    "level4_chunk1",
    "level4_chunk2",
    "level4_chunk3",
    "level4_chunk4",
    "level4_chunk5",
    "level4_chunk6",
    "level4_chunk7",
    "level4_chunk8",
    "level4_chunk9",
    "level4",
    "level5_chunk0",
    "level5_chunk10",
    "level5_chunk11",
    "level5_chunk12",
    "level5_chunk13",
    "level5_chunk1",
    "level5_chunk2",
    "level5_chunk3",
    "level5_chunk4",
    "level5_chunk5",
    "level5_chunk6",
    "level5_chunk7",
    "level5_chunk8",
    "level5_chunk9",
    "level5",
    "level6_chunk0",
    "level6_chunk10",
    "level6_chunk11",
    "level6_chunk12",
    "level6_chunk1",
    "level6_chunk2",
    "level6_chunk3",
    "level6_chunk4",
    "level6_chunk5",
    "level6_chunk6",
    "level6_chunk7",
    "level6_chunk8",
    "level6_chunk9",
    "level6",
    "level7_chunk0",
    "level7_chunk1",
    "level7_chunk2",
    "level7_chunk3",
    "level7_chunk4",
    "level7_chunk5",
    "level7_chunk6",
    "level7_chunk7",
    "level7",
    "rat",
    "slime",
    "spike",
    "spikes",
    "test_map",
};

#define COLLISION_NAME_COUNT 121

// Chunk group definitions (for models split into multiple chunks)
typedef struct {
    const char* baseName;
    int chunkCount;
} CollisionChunkGroupDef;

static const CollisionChunkGroupDef collision_chunk_group_defs[] = {
    { "level2", 13 },
    { "level3", 8 },
    { "level4", 13 },
    { "level5", 14 },
    { "level6", 13 },
    { "level7", 8 },
};

#define COLLISION_CHUNK_GROUP_COUNT 6

// ============================================================
// COLLISION LOOKUP FUNCTIONS
// ============================================================

// Lookup collision by model name - loads from ROM if not already loaded
static inline CollisionMesh* collision_find(const char* name) {
    return collision_load(name);
}

// Find all collision chunks for a model (returns chunk count, fills outChunks array)
// Returns 0 if no chunks found (use collision_find instead for single mesh)
static inline int collision_find_chunks(const char* name, CollisionMesh** outChunks, int maxChunks) {
    // Find the chunk group
    for (int i = 0; i < COLLISION_CHUNK_GROUP_COUNT; i++) {
        if (strcmp(collision_chunk_group_defs[i].baseName, name) == 0) {
            int count = collision_chunk_group_defs[i].chunkCount;
            if (count > maxChunks) count = maxChunks;

            // Load each chunk
            char chunkName[80];  // Enough for longest model name + "_chunk" + digits
            for (int j = 0; j < count; j++) {
                snprintf(chunkName, sizeof(chunkName), "%s_chunk%d", name, j);
                outChunks[j] = collision_load(chunkName);
                if (!outChunks[j]) {
                    debugf("Failed to load collision chunk: %s\n", chunkName);
                }
            }
            return count;
        }
    }
    return 0;
}

// Find a single collision chunk by full name (e.g., "level1_chunk0")
// Returns NULL if not found
static inline CollisionMesh* collision_find_single_chunk(const char* fullName) {
    return collision_load(fullName);
}

// Extract model name from path (e.g., "rom:/test_map.t3dm" -> "test_map")
static inline const char* extract_model_name(const char* path, char* buffer, int bufferSize) {
    const char* start = path;
    const char* slash = strrchr(path, '/');
    if (slash) start = slash + 1;

    int i = 0;
    while (start[i] && start[i] != '.' && i < bufferSize - 1) {
        buffer[i] = start[i];
        i++;
    }
    buffer[i] = '\0';
    return buffer;
}

#endif // COLLISION_REGISTRY_H
