#ifndef SOUNDS_GENERATED_H
#define SOUNDS_GENERATED_H

// ============================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by tools/generate_sounds_registry.py
// ============================================================
// This file contains arrays of music and SFX tracks for the jukebox.
// To add/remove tracks, edit JUKEBOX_MUSIC and JUKEBOX_SFX in the Makefile.
// ============================================================

// Music tracks (10 total)
#define JUKEBOX_MUSIC_COUNT 10

static const char* JUKEBOX_MUSIC[] = {
    "rom:/scrap1.wav64",
    "rom:/scrap1-menu(full).wav64",
    "rom:/scrap1-level1(full).wav64",
    "rom:/android64break.wav64",
    "rom:/androidjungle1.wav64",
    "rom:/CalmJunglescrap.wav64",
    "rom:/androidbreak2(finished).wav64",
    "rom:/N64GameJamIdea1.wav64",
    "rom:/N64Chiller3.wav64",
    "rom:/N64JetForceTrack.wav64",
};

static const char* JUKEBOX_MUSIC_NAMES[] = {
    "Scrapyard Theme",
    "Cartridge In, Feelings Out",
    "Synths Before Sentience",
    "Expansion Pak Installed",
    "OVERCLOCKED",
    "Low-Poly Love",
    "Byte Me",
    "Nut & Bolted",
    "Hardwired Heart",
    "Silicon Grief",
};

// SFX tracks (44 total)
#define JUKEBOX_SFX_COUNT 44

static const char* JUKEBOX_SFX[] = {
    "rom:/BoltCollected.wav64",
    "rom:/N64_Press_A_5.wav64",
    "rom:/N64UIHover4.wav64",
    "rom:/321Go1.wav64",
    "rom:/321Go2.wav64",
    "rom:/321Go3.wav64",
    "rom:/321Go4.wav64",
    "rom:/FireworkExplosion1.wav64",
    "rom:/FireworkExplosion2.wav64",
    "rom:/FireworkExplosion3.wav64",
    "rom:/FireworkSetOff.wav64",
    "rom:/FireworkSetOff2.wav64",
    "rom:/Jump1.wav64",
    "rom:/JumporLand.wav64",
    "rom:/JumpSound.wav64",
    "rom:/Landing1.wav64",
    "rom:/Landing2.wav64",
    "rom:/MiscDamage.wav64",
    "rom:/MiscDamage2.wav64",
    "rom:/Misc_Zap_1.wav64",
    "rom:/RatDamage.wav64",
    "rom:/RobotBeep.wav64",
    "rom:/RobotBeep2.wav64",
    "rom:/RobotBeepsandBoops.wav64",
    "rom:/RobotBoop.wav64",
    "rom:/RobotBoop2.wav64",
    "rom:/RobotDamage2.wav64",
    "rom:/RobotDamage3.wav64",
    "rom:/RobotHittingGround1.wav64",
    "rom:/RobotHittingGround2.wav64",
    "rom:/RobotHittingGround3.wav64",
    "rom:/RobotHittingGround4.wav64",
    "rom:/RobotHittingGround5.wav64",
    "rom:/RobotTakeDamage.wav64",
    "rom:/RobotTumble.wav64",
    "rom:/Slide1.wav64",
    "rom:/Slide2.wav64",
    "rom:/Slide3.wav64",
    "rom:/SlimeDamage.wav64",
    "rom:/SpinAttack1.wav64",
    "rom:/SpinAttack2.wav64",
    "rom:/SpinAttack3.wav64",
    "rom:/Turret_Fire.wav64",
    "rom:/WalkingonArms.wav64",
};

static const char* JUKEBOX_SFX_NAMES[] = {
    "Bolt Collected",
    "Confirm",
    "UI Hover",
    "321Go1",
    "321Go2",
    "321Go3",
    "321Go4",
    "Firework Explosion1",
    "Firework Explosion2",
    "Firework Explosion3",
    "Firework Set Off",
    "Firework Set Off2",
    "Jump1",
    "Jumpor Land",
    "Jump Sound",
    "Landing1",
    "Landing2",
    "Misc Damage",
    "Misc Damage2",
    "Misc Zap 1",
    "Rat Damage",
    "Robot Beep",
    "Robot Beep2",
    "Robot Beepsand Boops",
    "Robot Boop",
    "Robot Boop2",
    "Robot Damage2",
    "Robot Damage3",
    "Robot Hitting Ground1",
    "Robot Hitting Ground2",
    "Robot Hitting Ground3",
    "Robot Hitting Ground4",
    "Robot Hitting Ground5",
    "Robot Take Damage",
    "Robot Tumble",
    "Slide1",
    "Slide2",
    "Slide3",
    "Slime Damage",
    "Spin Attack1",
    "Spin Attack2",
    "Spin Attack3",
    "Turret Fire",
    "Walkingon Arms",
};

#endif // SOUNDS_GENERATED_H
